import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-russia";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Russia [2026]",
  description: "Discover the 50 most visited websites in Russia in 2026, ranked by estimated monthly visits. See how Yandex, VK, Mail.ru and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Russia [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Russia in 2026, ranked by estimated monthly visits. See how Yandex, VK, Mail.ru and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Russia [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Russia in 2026, ranked by estimated monthly visits. See how Yandex, VK, Mail.ru and more compare.",
  },
  robots: {
    index: false,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Russia",
  year: "2026",
  introduction: "Russia has over 120 million internet users, and its web traffic in 2026 reflects dominated by local giants like Yandex, VK, and Mail.ru. This ranking lists the 50 most visited websites in Russia for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Yandex",
      type: "Search Engine",
      monthlyVisits: "4.8B",
      monthlyVisitsValue: 4800,
      change: "+1.5%",
      changeValue: 1.5,
      description: "Russia's leading search engine and technology company.",
    },
    {
      rank: 2,
      name: "VK",
      type: "Social Network",
      monthlyVisits: "3.5B",
      monthlyVisitsValue: 3500,
      change: "+0.8%",
      changeValue: 0.8,
      description: "Russia's dominant social networking platform.",
    },
    {
      rank: 3,
      name: "Mail.ru",
      type: "Portal",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "-0.5%",
      changeValue: -0.5,
      description: "Russia's leading web portal offering email, news, and social services.",
    },
    {
      rank: 4,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+3.2%",
      changeValue: 3.2,
      description: "The dominant video platform in Russia for entertainment, music, and education.",
    },
    {
      rank: 5,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "2.2B",
      monthlyVisitsValue: 2200,
      change: "+1.0%",
      changeValue: 1.0,
      description: "The leading search engine in Russia, handling the vast majority of Russian web queries.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Russian students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Odnoklassniki",
      type: "Social Network",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "-1.0%",
      changeValue: -1.0,
      description: "A social networking platform widely used across Russia.",
    },
    {
      rank: 8,
      name: "Telegram",
      type: "Messaging",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+5.5%",
      changeValue: 5.5,
      description: "A messaging platform whose web client is used in Russia.",
    },
    {
      rank: 9,
      name: "Drom",
      type: "Automotive",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+1.2%",
      changeValue: 1.2,
      description: "An automotive marketplace for new and used cars in Russia.",
    },
    {
      rank: 10,
      name: "Avito",
      type: "Classifieds",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A classifieds platform for buying and selling in Russia.",
    },
    {
      rank: 11,
      name: "Wildberries",
      type: "E-commerce",
      monthlyVisits: "650M",
      monthlyVisitsValue: 650,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A popular online shopping destination in Russia for various products.",
    },
    {
      rank: 12,
      name: "Ozon",
      type: "E-commerce",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+3.8%",
      changeValue: 3.8,
      description: "A popular online shopping destination in Russia for various products.",
    },
    {
      rank: 13,
      name: "AliExpress",
      type: "E-commerce",
      monthlyVisits: "520M",
      monthlyVisitsValue: 520,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A popular online shopping destination in Russia for various products.",
    },
    {
      rank: 14,
      name: "Lamoda",
      type: "E-commerce",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A popular online shopping destination in Russia for various products.",
    },
    {
      rank: 15,
      name: "Sportmaster",
      type: "Retail",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A retail brand's online store in Russia.",
    },
    {
      rank: 16,
      name: "Mvideo",
      type: "Retail",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in Russia.",
    },
    {
      rank: 17,
      name: "Eldorado",
      type: "Retail",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Russia.",
    },
    {
      rank: 18,
      name: "Citilink",
      type: "Retail",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A retail brand's online store in Russia.",
    },
    {
      rank: 19,
      name: "DNS",
      type: "Retail",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A retail brand's online store in Russia.",
    },
    {
      rank: 20,
      name: "Sberbank",
      type: "Banking",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading bank's online banking portal in Russia.",
    },
    {
      rank: 21,
      name: "Tinkoff",
      type: "Banking",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A leading bank's online banking portal in Russia.",
    },
    {
      rank: 22,
      name: "VTB",
      type: "Banking",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Russia.",
    },
    {
      rank: 23,
      name: "Alfa-Bank",
      type: "Banking",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Russia.",
    },
    {
      rank: 24,
      name: "Gazprombank",
      type: "Banking",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Russia.",
    },
    {
      rank: 25,
      name: "RBC",
      type: "Business News",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A business news publication in Russia.",
    },
    {
      rank: 26,
      name: "Lenta.ru",
      type: "News",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Russian and international headlines.",
    },
    {
      rank: 27,
      name: "RIA Novosti",
      type: "News",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Russian and international headlines.",
    },
    {
      rank: 28,
      name: "TASS",
      type: "News",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Russian and international headlines.",
    },
    {
      rank: 29,
      name: "Interfax",
      type: "Business News",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A business news publication in Russia.",
    },
    {
      rank: 30,
      name: "Vedomosti",
      type: "Business News",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A business news publication in Russia.",
    },
    {
      rank: 31,
      name: "Kommersant",
      type: "Business News",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A business news publication in Russia.",
    },
    {
      rank: 32,
      name: "Izvestia",
      type: "News",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Russian and international headlines.",
    },
    {
      rank: 33,
      name: "Russia Today",
      type: "News",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A major news website covering Russian and international headlines.",
    },
    {
      rank: 34,
      name: "Channel One",
      type: "Media",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Russia.",
    },
    {
      rank: 35,
      name: "VGTRK",
      type: "Media",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Russia.",
    },
    {
      rank: 36,
      name: "NTV",
      type: "Media",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Russia.",
    },
    {
      rank: 37,
      name: "Match TV",
      type: "Sports",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A sports media site covering Russian and international sports.",
    },
    {
      rank: 38,
      name: "KinoPoisk",
      type: "Streaming",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A streaming service popular among Russian viewers.",
    },
    {
      rank: 39,
      name: "IVI",
      type: "Streaming",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A streaming service popular among Russian viewers.",
    },
    {
      rank: 40,
      name: "Okko",
      type: "Streaming",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A streaming service popular among Russian viewers.",
    },
    {
      rank: 41,
      name: "Auto.ru",
      type: "Automotive",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+0.8%",
      changeValue: 0.8,
      description: "An automotive marketplace for new and used cars in Russia.",
    },
    {
      rank: 42,
      name: "Cian",
      type: "Real Estate",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A property listing portal popular in Russia.",
    },
    {
      rank: 43,
      name: "HH.ru",
      type: "Job Portal",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A job search platform connecting Russian professionals with employers.",
    },
    {
      rank: 44,
      name: "Superjob",
      type: "Job Portal",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A job search platform connecting Russian professionals with employers.",
    },
    {
      rank: 45,
      name: "Rabota.ru",
      type: "Job Portal",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A job search platform connecting Russian professionals with employers.",
    },
    {
      rank: 46,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A global accommodation booking platform widely used by Russian travelers.",
    },
    {
      rank: 47,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "-0.8%",
      changeValue: -0.8,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 48,
      name: "Aviasales",
      type: "Travel",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A travel booking platform widely used by Russian travelers.",
    },
    {
      rank: 49,
      name: "Tutu",
      type: "Travel",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Russian travelers.",
    },
    {
      rank: 50,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "-5.0%",
      changeValue: -5.0,
      description: "A major social networking platform widely used across Russia for community and news.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Russia IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Yandex tops the list as the most visited website in Russia.",
    "E-commerce is led by Wildberries, Ozon, AliExpress, reflecting Russian shopping habits.",
    "Telegram shows the fastest growth at +5.5% month-over-month.",
    "News and media sites maintain strong daily traffic from Russian readers.",
    "Government and banking portals see steady usage across Russia.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Russia", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Russia in 2026?",
      answer: "In 2026, the most visited websites in Russia are led by Yandex, VK, Mail.ru, followed by Wildberries and local platforms like Odnoklassniki, Telegram, Drom. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Russia have in 2026?",
      answer: "Russia has over 120 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Russia?",
      answer: "Wildberries is the most visited e-commerce site in Russia, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Russia?",
      answer: "Google is among the most visited websites in Russia. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Russia?",
      answer: "The top local websites in Russia include Odnoklassniki, Telegram, Drom, which compete alongside global platforms for Russian users' attention.",
    },
    {
      question: "How is the traffic data for Russia websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Russia IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
