import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-spain";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Spain [2026]",
  description: "Discover the 50 most visited websites in Spain in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.es and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Spain [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Spain in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.es and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Spain [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Spain in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.es and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Spain",
  year: "2026",
  introduction: "Spain has over 45 million internet users, and its web traffic in 2026 reflects global platforms alongside domestic media and retail leaders. This ranking lists the 50 most visited websites in Spain for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "3.8B",
      monthlyVisitsValue: 3800,
      change: "+1.2%",
      changeValue: 1.2,
      description: "The leading search engine in Spain, handling the vast majority of Spanish web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The dominant video platform in Spain for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Amazon.es",
      type: "E-commerce",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+2.5%",
      changeValue: 2.5,
      description: "Amazon's Spanish storefront, a top online retailer in Spain.",
    },
    {
      rank: 4,
      name: "El Pais",
      type: "News",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 5,
      name: "Marca",
      type: "Sports",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A sports media site covering Spanish and international sports.",
    },
    {
      rank: 6,
      name: "AS",
      type: "Sports",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A sports media site covering Spanish and international sports.",
    },
    {
      rank: 7,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "-1.8%",
      changeValue: -1.8,
      description: "A major social networking platform widely used across Spain for community and news.",
    },
    {
      rank: 8,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "650M",
      monthlyVisitsValue: 650,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Spanish students, researchers, and readers.",
    },
    {
      rank: 9,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A fast-growing visual social platform popular among Spanish youth for reels and stories.",
    },
    {
      rank: 10,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "520M",
      monthlyVisitsValue: 520,
      change: "-1.5%",
      changeValue: -1.5,
      description: "The real-time public conversation platform widely used for news in Spain.",
    },
    {
      rank: 11,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Spanish original content.",
    },
    {
      rank: 12,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Spanish job seekers, recruiters, and B2B content.",
    },
    {
      rank: 13,
      name: "El Mundo",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 14,
      name: "ABC",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 15,
      name: "La Vanguardia",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 16,
      name: "El Confidencial",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 17,
      name: "20minutos",
      type: "News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 18,
      name: "El Espanol",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Spanish and international headlines.",
    },
    {
      rank: 19,
      name: "Cinco Dias",
      type: "Business News",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A business news publication in Spain.",
    },
    {
      rank: 20,
      name: "Expansion",
      type: "Business News",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A business news publication in Spain.",
    },
    {
      rank: 21,
      name: "SPORT",
      type: "Sports",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A sports media site covering Spanish and international sports.",
    },
    {
      rank: 22,
      name: "Mundo Deportivo",
      type: "Sports",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A sports media site covering Spanish and international sports.",
    },
    {
      rank: 23,
      name: "Movistar",
      type: "Telecom",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A telecommunications provider's official site in Spain.",
    },
    {
      rank: 24,
      name: "Orange",
      type: "Telecom",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A telecommunications provider's official site in Spain.",
    },
    {
      rank: 25,
      name: "Vodafone",
      type: "Telecom",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A telecommunications provider's official site in Spain.",
    },
    {
      rank: 26,
      name: "Yoigo",
      type: "Telecom",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A telecommunications provider's official site in Spain.",
    },
    {
      rank: 27,
      name: "Lowi",
      type: "Telecom",
      monthlyVisits: "75M",
      monthlyVisitsValue: 75,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A telecommunications provider's official site in Spain.",
    },
    {
      rank: 28,
      name: "BBVA",
      type: "Banking",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 29,
      name: "Santander",
      type: "Banking",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 30,
      name: "CaixaBank",
      type: "Banking",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 31,
      name: "Bankinter",
      type: "Banking",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 32,
      name: "Sabadell",
      type: "Banking",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 33,
      name: "ING",
      type: "Banking",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 34,
      name: "Bankia",
      type: "Banking",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 35,
      name: "Kutxabank",
      type: "Banking",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 36,
      name: "Ibercaja",
      type: "Banking",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A leading bank's online banking portal in Spain.",
    },
    {
      rank: 37,
      name: "Idealista",
      type: "Real Estate",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A property listing portal popular in Spain.",
    },
    {
      rank: 38,
      name: "Fotocasa",
      type: "Real Estate",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A property listing portal popular in Spain.",
    },
    {
      rank: 39,
      name: "Milanuncios",
      type: "Classifieds",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A classifieds platform for buying and selling in Spain.",
    },
    {
      rank: 40,
      name: "Wallapop",
      type: "Marketplace",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+3.5%",
      changeValue: 3.5,
      description: "An online marketplace popular in Spain.",
    },
    {
      rank: 41,
      name: "Carrefour",
      type: "Retail",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Spain.",
    },
    {
      rank: 42,
      name: "El Corte Ingles",
      type: "Retail",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A retail brand's online store in Spain.",
    },
    {
      rank: 43,
      name: "MediaMarkt",
      type: "Retail",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A retail brand's online store in Spain.",
    },
    {
      rank: 44,
      name: "PC Componentes",
      type: "Retail",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A retail brand's online store in Spain.",
    },
    {
      rank: 45,
      name: "Renfe",
      type: "Travel",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Spanish travelers.",
    },
    {
      rank: 46,
      name: "Iberia",
      type: "Travel",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A travel booking platform widely used by Spanish travelers.",
    },
    {
      rank: 47,
      name: "AENA",
      type: "Travel",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A travel booking platform widely used by Spanish travelers.",
    },
    {
      rank: 48,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A global accommodation booking platform widely used by Spanish travelers.",
    },
    {
      rank: 49,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "1.5M",
      monthlyVisitsValue: 1.5,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 50,
      name: "eDreams",
      type: "Travel",
      monthlyVisits: "1M",
      monthlyVisitsValue: 1,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Spanish travelers.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Spain IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Spain.",
    "E-commerce is led by Amazon.es, Wallapop, reflecting Spanish shopping habits.",
    "Instagram shows the fastest growth at +4.0% month-over-month.",
    "News and media sites maintain strong daily traffic from Spanish readers.",
    "Government and banking portals see steady usage across Spain.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Spain", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Spain in 2026?",
      answer: "In 2026, the most visited websites in Spain are led by Google, YouTube, Amazon.es, followed by Amazon.es and local platforms like El Pais, Marca, AS. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Spain have in 2026?",
      answer: "Spain has over 45 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Spain?",
      answer: "Amazon.es is the most visited e-commerce site in Spain, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Spain?",
      answer: "Google is among the most visited websites in Spain. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Spain?",
      answer: "The top local websites in Spain include El Pais, Marca, AS, which compete alongside global platforms for Spanish users' attention.",
    },
    {
      question: "How is the traffic data for Spain websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Spain IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
