import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-italy";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Italy [2026]",
  description: "Discover the 50 most visited websites in Italy in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.it and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Italy [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Italy in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.it and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Italy [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Italy in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.it and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Italy",
  year: "2026",
  introduction: "Italy has over 55 million internet users, and its web traffic in 2026 reflects global platforms alongside domestic news and retail leaders. This ranking lists the 50 most visited websites in Italy for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "4.2B",
      monthlyVisitsValue: 4200,
      change: "+1.2%",
      changeValue: 1.2,
      description: "The leading search engine in Italy, handling the vast majority of Italian web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "3.2B",
      monthlyVisitsValue: 3200,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The dominant video platform in Italy for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Amazon.it",
      type: "E-commerce",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+2.5%",
      changeValue: 2.5,
      description: "Amazon's Italian storefront, a leading online retailer in Italy.",
    },
    {
      rank: 4,
      name: "eBay",
      type: "Marketplace",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A major online marketplace for auctions, used goods, and collectibles.",
    },
    {
      rank: 5,
      name: "Subito",
      type: "Classifieds",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A classifieds platform for buying and selling in Italy.",
    },
    {
      rank: 6,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "-1.8%",
      changeValue: -1.8,
      description: "A major social networking platform widely used across Italy for community and news.",
    },
    {
      rank: 7,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Italian students, researchers, and readers.",
    },
    {
      rank: 8,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+4.2%",
      changeValue: 4.2,
      description: "A fast-growing visual social platform popular among Italian youth for reels and stories.",
    },
    {
      rank: 9,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "-1.5%",
      changeValue: -1.5,
      description: "The real-time public conversation platform widely used for news in Italy.",
    },
    {
      rank: 10,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "550M",
      monthlyVisitsValue: 550,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Italian original content.",
    },
    {
      rank: 11,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "500M",
      monthlyVisitsValue: 500,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Italian job seekers, recruiters, and B2B content.",
    },
    {
      rank: 12,
      name: "Corriere della Sera",
      type: "News",
      monthlyVisits: "450M",
      monthlyVisitsValue: 450,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 13,
      name: "Repubblica",
      type: "News",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 14,
      name: "La Stampa",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 15,
      name: "Il Sole 24 Ore",
      type: "Business News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A business news publication in Italy.",
    },
    {
      rank: 16,
      name: "Il Messaggero",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 17,
      name: "Il Fatto Quotidiano",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 18,
      name: "Libero",
      type: "News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 19,
      name: "Il Giornale",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "-0.1%",
      changeValue: -0.1,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 20,
      name: "ANSA",
      type: "News",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 21,
      name: "Sky Sport",
      type: "Sports",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A sports media site covering Italian and international sports.",
    },
    {
      rank: 22,
      name: "Gazzetta dello Sport",
      type: "Sports",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A sports media site covering Italian and international sports.",
    },
    {
      rank: 23,
      name: "Tgcom24",
      type: "News",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 24,
      name: "Sky TG24",
      type: "News",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Italian and international headlines.",
    },
    {
      rank: 25,
      name: "Rai",
      type: "Media",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in Italy.",
    },
    {
      rank: 26,
      name: "Mediaset",
      type: "Media",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Italy.",
    },
    {
      rank: 27,
      name: "La7",
      type: "Media",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A media company's digital platform in Italy.",
    },
    {
      rank: 28,
      name: "TIM",
      type: "Telecom",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A telecommunications provider's official site in Italy.",
    },
    {
      rank: 29,
      name: "Vodafone",
      type: "Telecom",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A telecommunications provider's official site in Italy.",
    },
    {
      rank: 30,
      name: "WindTre",
      type: "Telecom",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A telecommunications provider's official site in Italy.",
    },
    {
      rank: 31,
      name: "Iliad",
      type: "Telecom",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A telecommunications provider's official site in Italy.",
    },
    {
      rank: 32,
      name: "Fastweb",
      type: "Telecom",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A telecommunications provider's official site in Italy.",
    },
    {
      rank: 33,
      name: "UniCredit",
      type: "Banking",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Italy.",
    },
    {
      rank: 34,
      name: "Intesa Sanpaolo",
      type: "Banking",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Italy.",
    },
    {
      rank: 35,
      name: "BNL",
      type: "Banking",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Italy.",
    },
    {
      rank: 36,
      name: "BPM",
      type: "Banking",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Italy.",
    },
    {
      rank: 37,
      name: "Monte dei Paschi",
      type: "Banking",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A leading bank's online banking portal in Italy.",
    },
    {
      rank: 38,
      name: "Poste Italiane",
      type: "Services",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A services platform widely used in Italy.",
    },
    {
      rank: 39,
      name: "INPS",
      type: "Government",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.3%",
      changeValue: 0.3,
      description: "An official government service portal in Italy.",
    },
    {
      rank: 40,
      name: "ACI",
      type: "Services",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A services platform widely used in Italy.",
    },
    {
      rank: 41,
      name: "Trenitalia",
      type: "Travel",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A travel booking platform widely used by Italian travelers.",
    },
    {
      rank: 42,
      name: "Italo",
      type: "Travel",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Italian travelers.",
    },
    {
      rank: 43,
      name: "ITA Airways",
      type: "Travel",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A travel booking platform widely used by Italian travelers.",
    },
    {
      rank: 44,
      name: "Ryanair",
      type: "Travel",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A travel booking platform widely used by Italian travelers.",
    },
    {
      rank: 45,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A global accommodation booking platform widely used by Italian travelers.",
    },
    {
      rank: 46,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 47,
      name: "Idealista",
      type: "Real Estate",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A property listing portal popular in Italy.",
    },
    {
      rank: 48,
      name: "Immobiliare",
      type: "Real Estate",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A property listing portal popular in Italy.",
    },
    {
      rank: 49,
      name: "Subito",
      type: "Classifieds",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A classifieds platform for buying and selling in Italy.",
    },
    {
      rank: 50,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+3.5%",
      changeValue: 3.5,
      description: "Community-driven forums growing fast among Italian tech, finance, and gaming enthusiasts.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Italy IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Italy.",
    "E-commerce is led by Amazon.it, eBay, reflecting Italian shopping habits.",
    "Instagram shows the fastest growth at +4.2% month-over-month.",
    "News and media sites maintain strong daily traffic from Italian readers.",
    "Government and banking portals see steady usage across Italy.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Italy", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Italy in 2026?",
      answer: "In 2026, the most visited websites in Italy are led by Google, YouTube, Amazon.it, followed by Amazon.it and local platforms like Subito, Corriere della Sera, Repubblica. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Italy have in 2026?",
      answer: "Italy has over 55 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Italy?",
      answer: "Amazon.it is the most visited e-commerce site in Italy, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Italy?",
      answer: "Google is among the most visited websites in Italy. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Italy?",
      answer: "The top local websites in Italy include Subito, Corriere della Sera, Repubblica, which compete alongside global platforms for Italian users' attention.",
    },
    {
      question: "How is the traffic data for Italy websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Italy IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
