import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-turkey";
const PAGE_URL = `https://trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Turkey [2026]",
  description: "Discover the 50 most visited websites in Turkey in 2026, ranked by estimated monthly visits. See how Google, YouTube, Sahibinden and more compare.",
  metadataBase: new URL("https://trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Turkey [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Turkey in 2026, ranked by estimated monthly visits. See how Google, YouTube, Sahibinden and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Turkey [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Turkey in 2026, ranked by estimated monthly visits. See how Google, YouTube, Sahibinden and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Turkey",
  year: "2026",
  introduction: "Turkey has over 80 million internet users, and its web traffic in 2026 reflects global platforms alongside domestic e-commerce and media leaders. This ranking lists the 50 most visited websites in Turkey for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "3.5B",
      monthlyVisitsValue: 3500,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The leading search engine in Turkey, handling the vast majority of Turkish web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "+3.2%",
      changeValue: 3.2,
      description: "The dominant video platform in Turkey for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Sahibinden",
      type: "Classifieds",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+2.5%",
      changeValue: 2.5,
      description: "Turkey's leading classifieds platform for real estate, vehicles, and goods.",
    },
    {
      rank: 4,
      name: "Hepsiburada",
      type: "E-commerce",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+3.0%",
      changeValue: 3.0,
      description: "A major Turkish e-commerce platform offering a wide range of products.",
    },
    {
      rank: 5,
      name: "Trendyol",
      type: "E-commerce",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+5.5%",
      changeValue: 5.5,
      description: "Turkey's largest e-commerce platform, backed by Alibaba.",
    },
    {
      rank: 6,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "1.0B",
      monthlyVisitsValue: 1000,
      change: "-1.5%",
      changeValue: -1.5,
      description: "A major social networking platform widely used across Turkey for community and news.",
    },
    {
      rank: 7,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "880M",
      monthlyVisitsValue: 880,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Turkish students, researchers, and readers.",
    },
    {
      rank: 8,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A fast-growing visual social platform popular among Turkish youth for reels and stories.",
    },
    {
      rank: 9,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "-1.2%",
      changeValue: -1.2,
      description: "The real-time public conversation platform widely used for news in Turkey.",
    },
    {
      rank: 10,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "550M",
      monthlyVisitsValue: 550,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Turkish original content.",
    },
    {
      rank: 11,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Turkish job seekers, recruiters, and B2B content.",
    },
    {
      rank: 12,
      name: "Hurriyet",
      type: "News",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 13,
      name: "Milliyet",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 14,
      name: "Sözcü",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 15,
      name: "Sabah",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 16,
      name: "Posta",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 17,
      name: "CNN Türk",
      type: "News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 18,
      name: "NTV",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Turkish and international headlines.",
    },
    {
      rank: 19,
      name: "TRT",
      type: "Media",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 20,
      name: "Show TV",
      type: "Media",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 21,
      name: "Star TV",
      type: "Media",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 22,
      name: "Kanal D",
      type: "Media",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 23,
      name: "Fox Turkey",
      type: "Media",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 24,
      name: "TV8",
      type: "Media",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 25,
      name: "Beyaz TV",
      type: "Media",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A media company's digital platform in Turkey.",
    },
    {
      rank: 26,
      name: "TCDD",
      type: "Travel",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A travel booking platform widely used by Turkish travelers.",
    },
    {
      rank: 27,
      name: "Turkish Airlines",
      type: "Travel",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Turkish travelers.",
    },
    {
      rank: 28,
      name: "Pegasus",
      type: "Travel",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A travel booking platform widely used by Turkish travelers.",
    },
    {
      rank: 29,
      name: "Enpara",
      type: "Banking",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A leading bank's online banking portal in Turkey.",
    },
    {
      rank: 30,
      name: "Garanti BBVA",
      type: "Banking",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Turkey.",
    },
    {
      rank: 31,
      name: "Akbank",
      type: "Banking",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Turkey.",
    },
    {
      rank: 32,
      name: "Yapi Kredi",
      type: "Banking",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Turkey.",
    },
    {
      rank: 33,
      name: "Ziraat",
      type: "Banking",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Turkey.",
    },
    {
      rank: 34,
      name: "Is Bankasi",
      type: "Banking",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A leading bank's online banking portal in Turkey.",
    },
    {
      rank: 35,
      name: "BIM",
      type: "Retail",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 36,
      name: "A101",
      type: "Retail",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 37,
      name: "Sok",
      type: "Retail",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 38,
      name: "Migros",
      type: "Retail",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 39,
      name: "CarrefourSA",
      type: "Retail",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 40,
      name: "Watsons",
      type: "Retail",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 41,
      name: "Gratis",
      type: "Retail",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A retail brand's online store in Turkey.",
    },
    {
      rank: 42,
      name: "Getir",
      type: "Services",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A services platform widely used in Turkey.",
    },
    {
      rank: 43,
      name: "Yemeksepeti",
      type: "Food Delivery",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A food delivery and restaurant discovery platform in Turkey.",
    },
    {
      rank: 44,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A global accommodation booking platform widely used by Turkish travelers.",
    },
    {
      rank: 45,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 46,
      name: "Hepsiemlak",
      type: "Real Estate",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A property listing portal popular in Turkey.",
    },
    {
      rank: 47,
      name: "Hurriyet Emlak",
      type: "Real Estate",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A property listing portal popular in Turkey.",
    },
    {
      rank: 48,
      name: "N11",
      type: "Marketplace",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.5%",
      changeValue: 0.5,
      description: "An online marketplace popular in Turkey.",
    },
    {
      rank: 49,
      name: "GittiGidiyor",
      type: "Marketplace",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "-0.5%",
      changeValue: -0.5,
      description: "An online marketplace popular in Turkey.",
    },
    {
      rank: 50,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "1.5M",
      monthlyVisitsValue: 1.5,
      change: "+3.0%",
      changeValue: 3.0,
      description: "Community-driven forums growing fast among Turkish tech, finance, and gaming enthusiasts.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Turkey IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Turkey.",
    "E-commerce is led by Hepsiburada, Trendyol, N11, reflecting Turkish shopping habits.",
    "Trendyol shows the fastest growth at +5.5% month-over-month.",
    "News and media sites maintain strong daily traffic from Turkish readers.",
    "Government and banking portals see steady usage across Turkey.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Turkey", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Turkey in 2026?",
      answer: "In 2026, the most visited websites in Turkey are led by Google, YouTube, Sahibinden, followed by Hepsiburada and local platforms like Hurriyet, Milliyet, Sözcü. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Turkey have in 2026?",
      answer: "Turkey has over 80 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Turkey?",
      answer: "Hepsiburada is the most visited e-commerce site in Turkey, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Turkey?",
      answer: "Google is among the most visited websites in Turkey. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Turkey?",
      answer: "The top local websites in Turkey include Hurriyet, Milliyet, Sözcü, which compete alongside global platforms for Turkish users' attention.",
    },
    {
      question: "How is the traffic data for Turkey websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Turkey IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
