import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-mexico";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Mexico [2026]",
  description: "Discover the 50 most visited websites in Mexico in 2026, ranked by estimated monthly visits. See how Google, YouTube, MercadoLibre and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Mexico [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Mexico in 2026, ranked by estimated monthly visits. See how Google, YouTube, MercadoLibre and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Mexico [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Mexico in 2026, ranked by estimated monthly visits. See how Google, YouTube, MercadoLibre and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Mexico",
  year: "2026",
  introduction: "Mexico has over 95 million internet users, and its web traffic in 2026 reflects global platforms alongside domestic media and retail leaders. This ranking lists the 50 most visited websites in Mexico for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "3.5B",
      monthlyVisitsValue: 3500,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The leading search engine in Mexico, handling the vast majority of Mexican web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "+3.2%",
      changeValue: 3.2,
      description: "The dominant video platform in Mexico for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "MercadoLibre",
      type: "E-commerce",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A popular online shopping destination in Mexico for various products.",
    },
    {
      rank: 4,
      name: "Amazon Mexico",
      type: "E-commerce",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+3.5%",
      changeValue: 3.5,
      description: "Amazon's Mexican storefront, competing with MercadoLibre.",
    },
    {
      rank: 5,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "1.0B",
      monthlyVisitsValue: 1000,
      change: "-1.5%",
      changeValue: -1.5,
      description: "A major social networking platform widely used across Mexico for community and news.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "880M",
      monthlyVisitsValue: 880,
      change: "+0.6%",
      changeValue: 0.6,
      description: "The free encyclopedia accessed heavily by Mexican students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A fast-growing visual social platform popular among Mexican youth for reels and stories.",
    },
    {
      rank: 8,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "-1.2%",
      changeValue: -1.2,
      description: "The real-time public conversation platform widely used for news in Mexico.",
    },
    {
      rank: 9,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "550M",
      monthlyVisitsValue: 550,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Mexican original content.",
    },
    {
      rank: 10,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Mexican job seekers, recruiters, and B2B content.",
    },
    {
      rank: 11,
      name: "El Universal",
      type: "News",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Mexican and international headlines.",
    },
    {
      rank: 12,
      name: "Reforma",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Mexican and international headlines.",
    },
    {
      rank: 13,
      name: "Excelsior",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering Mexican and international headlines.",
    },
    {
      rank: 14,
      name: "Milenio",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Mexican and international headlines.",
    },
    {
      rank: 15,
      name: "La Jornada",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Mexican and international headlines.",
    },
    {
      rank: 16,
      name: "El Financiero",
      type: "Business News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A business news publication in Mexico.",
    },
    {
      rank: 17,
      name: "Televisa",
      type: "Media",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in Mexico.",
    },
    {
      rank: 18,
      name: "TV Azteca",
      type: "Media",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Mexico.",
    },
    {
      rank: 19,
      name: "Imagen",
      type: "Media",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A media company's digital platform in Mexico.",
    },
    {
      rank: 20,
      name: "Las Estrellas",
      type: "Media",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A media company's digital platform in Mexico.",
    },
    {
      rank: 21,
      name: "Canal 5",
      type: "Media",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Mexico.",
    },
    {
      rank: 22,
      name: "Azteca 7",
      type: "Media",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Mexico.",
    },
    {
      rank: 23,
      name: "Mercado Pago",
      type: "Fintech",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A financial technology platform popular in Mexico.",
    },
    {
      rank: 24,
      name: "BBVA Bancomer",
      type: "Banking",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading bank's online banking portal in Mexico.",
    },
    {
      rank: 25,
      name: "Santander Mexico",
      type: "Banking",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Mexico.",
    },
    {
      rank: 26,
      name: "Banorte",
      type: "Banking",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Mexico.",
    },
    {
      rank: 27,
      name: "Citibanamex",
      type: "Banking",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Mexico.",
    },
    {
      rank: 28,
      name: "HSBC Mexico",
      type: "Banking",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Mexico.",
    },
    {
      rank: 29,
      name: "OXXO",
      type: "Retail",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A retail brand's online store in Mexico.",
    },
    {
      rank: 30,
      name: "Soriana",
      type: "Retail",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Mexico.",
    },
    {
      rank: 31,
      name: "Chedraui",
      type: "Retail",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A retail brand's online store in Mexico.",
    },
    {
      rank: 32,
      name: "Walmart Mexico",
      type: "Retail",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A retail brand's online store in Mexico.",
    },
    {
      rank: 33,
      name: "Liverpool",
      type: "Retail",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A retail brand's online store in Mexico.",
    },
    {
      rank: 34,
      name: "Palacio de Hierro",
      type: "Retail",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A retail brand's online store in Mexico.",
    },
    {
      rank: 35,
      name: "Cinepolis",
      type: "Entertainment",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+1.0%",
      changeValue: 1.0,
      description: "An entertainment platform popular in Mexico.",
    },
    {
      rank: 36,
      name: "Cinemex",
      type: "Entertainment",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.8%",
      changeValue: 0.8,
      description: "An entertainment platform popular in Mexico.",
    },
    {
      rank: 37,
      name: "Viva Aerobus",
      type: "Travel",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A travel booking platform widely used by Mexican travelers.",
    },
    {
      rank: 38,
      name: "Volaris",
      type: "Travel",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A travel booking platform widely used by Mexican travelers.",
    },
    {
      rank: 39,
      name: "Aeromexico",
      type: "Travel",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A travel booking platform widely used by Mexican travelers.",
    },
    {
      rank: 40,
      name: "ADO",
      type: "Travel",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A travel booking platform widely used by Mexican travelers.",
    },
    {
      rank: 41,
      name: "SAT",
      type: "Government",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.3%",
      changeValue: 0.3,
      description: "An official government service portal in Mexico.",
    },
    {
      rank: 42,
      name: "IMSS",
      type: "Government",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+0.4%",
      changeValue: 0.4,
      description: "An official government service portal in Mexico.",
    },
    {
      rank: 43,
      name: "ISSSTE",
      type: "Government",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+0.2%",
      changeValue: 0.2,
      description: "An official government service portal in Mexico.",
    },
    {
      rank: 44,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A global accommodation booking platform widely used by Mexican travelers.",
    },
    {
      rank: 45,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 46,
      name: "Despegar",
      type: "Travel",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A travel booking platform widely used by Mexican travelers.",
    },
    {
      rank: 47,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+3.5%",
      changeValue: 3.5,
      description: "Community-driven forums growing fast among Mexican tech, finance, and gaming enthusiasts.",
    },
    {
      rank: 48,
      name: "TikTok",
      type: "Social Network",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+8.5%",
      changeValue: 8.5,
      description: "A fast-growing short-video platform dominating Mexican youth attention.",
    },
    {
      rank: 49,
      name: "WhatsApp",
      type: "Messaging",
      monthlyVisits: "1.5M",
      monthlyVisitsValue: 1.5,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading messaging app whose web client is accessed by millions in Mexico.",
    },
    {
      rank: 50,
      name: "PayPal",
      type: "Fintech",
      monthlyVisits: "1M",
      monthlyVisitsValue: 1,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading online payment platform widely used for e-commerce in Mexico.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Mexico IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Mexico.",
    "E-commerce is led by MercadoLibre, Amazon Mexico, reflecting Mexican shopping habits.",
    "TikTok shows the fastest growth at +8.5% month-over-month.",
    "News and media sites maintain strong daily traffic from Mexican readers.",
    "Government and banking portals see steady usage across Mexico.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Mexico", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Mexico in 2026?",
      answer: "In 2026, the most visited websites in Mexico are led by Google, YouTube, MercadoLibre, followed by MercadoLibre and local platforms like MercadoLibre, El Universal, Reforma. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Mexico have in 2026?",
      answer: "Mexico has over 95 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Mexico?",
      answer: "MercadoLibre is the most visited e-commerce site in Mexico, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Mexico?",
      answer: "Google is among the most visited websites in Mexico. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Mexico?",
      answer: "The top local websites in Mexico include MercadoLibre, El Universal, Reforma, which compete alongside global platforms for Mexican users' attention.",
    },
    {
      question: "How is the traffic data for Mexico websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Mexico IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
