import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-germany";
const PAGE_URL = `https://trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Germany [2026]",
  description: "Discover the 50 most visited websites in Germany in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.de and more compare.",
  metadataBase: new URL("https://trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Germany [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Germany in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.de and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Germany [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Germany in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.de and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Germany",
  year: "2026",
  introduction: "Germany has over 78 million internet users, and its web traffic in 2026 reflects strong domestic media alongside global platforms. This ranking lists the 50 most visited websites in Germany for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "6.8B",
      monthlyVisitsValue: 6800,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The leading search engine in Germany, handling the vast majority of German web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "5.2B",
      monthlyVisitsValue: 5200,
      change: "+3.1%",
      changeValue: 3.1,
      description: "The dominant video platform in Germany for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Amazon.de",
      type: "E-commerce",
      monthlyVisits: "3.8B",
      monthlyVisitsValue: 3800,
      change: "+2.8%",
      changeValue: 2.8,
      description: "Amazon's German storefront, the largest online retailer in the country.",
    },
    {
      rank: 4,
      name: "eBay Kleinanzeigen",
      type: "Classifieds",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A classifieds platform for buying and selling in Germany.",
    },
    {
      rank: 5,
      name: "Bild",
      type: "News",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "1.6B",
      monthlyVisitsValue: 1600,
      change: "+0.8%",
      changeValue: 0.8,
      description: "The free encyclopedia accessed heavily by German students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "1.4B",
      monthlyVisitsValue: 1400,
      change: "-2.0%",
      changeValue: -2.0,
      description: "A major social networking platform widely used across Germany for community and news.",
    },
    {
      rank: 8,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A fast-growing visual social platform popular among German youth for reels and stories.",
    },
    {
      rank: 9,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+5.8%",
      changeValue: 5.8,
      description: "Community-driven forums growing fast among German tech, finance, and gaming enthusiasts.",
    },
    {
      rank: 10,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "-1.5%",
      changeValue: -1.5,
      description: "The real-time public conversation platform widely used for news in Germany.",
    },
    {
      rank: 11,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+2.3%",
      changeValue: 2.3,
      description: "A premium streaming service investing in German original content.",
    },
    {
      rank: 12,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for German job seekers, recruiters, and B2B content.",
    },
    {
      rank: 13,
      name: "Spotify Germany",
      type: "Music",
      monthlyVisits: "650M",
      monthlyVisitsValue: 650,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A music streaming service popular in Germany.",
    },
    {
      rank: 14,
      name: "Welt",
      type: "News",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 15,
      name: "Spiegel",
      type: "News",
      monthlyVisits: "540M",
      monthlyVisitsValue: 540,
      change: "+1.1%",
      changeValue: 1.1,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 16,
      name: "Focus",
      type: "News",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 17,
      name: "RTL",
      type: "Media",
      monthlyVisits: "440M",
      monthlyVisitsValue: 440,
      change: "+1.4%",
      changeValue: 1.4,
      description: "A media company's digital platform in Germany.",
    },
    {
      rank: 18,
      name: "ProSieben",
      type: "Media",
      monthlyVisits: "400M",
      monthlyVisitsValue: 400,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A media company's digital platform in Germany.",
    },
    {
      rank: 19,
      name: "Xing",
      type: "Professional Network",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+1.6%",
      changeValue: 1.6,
      description: "A professional networking platform in Germany.",
    },
    {
      rank: 20,
      name: "Idealo",
      type: "Price Comparison",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+2.2%",
      changeValue: 2.2,
      description: "A price comparison site popular in Germany.",
    },
    {
      rank: 21,
      name: "Check24",
      type: "Price Comparison",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+1.9%",
      changeValue: 1.9,
      description: "A price comparison site popular in Germany.",
    },
    {
      rank: 22,
      name: "Otto",
      type: "E-commerce",
      monthlyVisits: "290M",
      monthlyVisitsValue: 290,
      change: "+1.3%",
      changeValue: 1.3,
      description: "A popular online shopping destination in Germany for various products.",
    },
    {
      rank: 23,
      name: "Zalando",
      type: "E-commerce",
      monthlyVisits: "270M",
      monthlyVisitsValue: 270,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A popular online shopping destination in Germany for various products.",
    },
    {
      rank: 24,
      name: "MediaMarkt",
      type: "Retail",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in Germany.",
    },
    {
      rank: 25,
      name: "Saturn",
      type: "Retail",
      monthlyVisits: "230M",
      monthlyVisitsValue: 230,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Germany.",
    },
    {
      rank: 26,
      name: "Telekom",
      type: "Telecom",
      monthlyVisits: "210M",
      monthlyVisitsValue: 210,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A telecommunications provider's official site in Germany.",
    },
    {
      rank: 27,
      name: "Vodafone",
      type: "Telecom",
      monthlyVisits: "195M",
      monthlyVisitsValue: 195,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A telecommunications provider's official site in Germany.",
    },
    {
      rank: 28,
      name: "O2",
      type: "Telecom",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A telecommunications provider's official site in Germany.",
    },
    {
      rank: 29,
      name: "Lidl",
      type: "Retail",
      monthlyVisits: "165M",
      monthlyVisitsValue: 165,
      change: "+2.1%",
      changeValue: 2.1,
      description: "A retail brand's online store in Germany.",
    },
    {
      rank: 30,
      name: "Aldi",
      type: "Retail",
      monthlyVisits: "150M",
      monthlyVisitsValue: 150,
      change: "+1.8%",
      changeValue: 1.8,
      description: "A retail brand's online store in Germany.",
    },
    {
      rank: 31,
      name: "Kaufland",
      type: "Retail",
      monthlyVisits: "135M",
      monthlyVisitsValue: 135,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in Germany.",
    },
    {
      rank: 32,
      name: "Rewe",
      type: "Retail",
      monthlyVisits: "125M",
      monthlyVisitsValue: 125,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A retail brand's online store in Germany.",
    },
    {
      rank: 33,
      name: "Deutsche Bahn",
      type: "Travel",
      monthlyVisits: "115M",
      monthlyVisitsValue: 115,
      change: "+2.4%",
      changeValue: 2.4,
      description: "A travel booking platform widely used by German travelers.",
    },
    {
      rank: 34,
      name: "Immobilienscout24",
      type: "Real Estate",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+1.7%",
      changeValue: 1.7,
      description: "A property listing portal popular in Germany.",
    },
    {
      rank: 35,
      name: "Mobile.de",
      type: "Automotive",
      monthlyVisits: "98M",
      monthlyVisitsValue: 98,
      change: "+1.1%",
      changeValue: 1.1,
      description: "An automotive marketplace for new and used cars in Germany.",
    },
    {
      rank: 36,
      name: "Autoscout24",
      type: "Automotive",
      monthlyVisits: "92M",
      monthlyVisitsValue: 92,
      change: "+1.3%",
      changeValue: 1.3,
      description: "An automotive marketplace for new and used cars in Germany.",
    },
    {
      rank: 37,
      name: "Stepstone",
      type: "Job Portal",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A job search platform connecting German professionals with employers.",
    },
    {
      rank: 38,
      name: "Indeed Germany",
      type: "Job Portal",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+1.6%",
      changeValue: 1.6,
      description: "A job search platform connecting German professionals with employers.",
    },
    {
      rank: 39,
      name: "Die Zeit",
      type: "News",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 40,
      name: "FAZ",
      type: "News",
      monthlyVisits: "68M",
      monthlyVisitsValue: 68,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 41,
      name: "Sueddeutsche",
      type: "News",
      monthlyVisits: "62M",
      monthlyVisitsValue: 62,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 42,
      name: "Tagesschau",
      type: "News",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A major news website covering German and international headlines.",
    },
    {
      rank: 43,
      name: "ARD",
      type: "Media",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A media company's digital platform in Germany.",
    },
    {
      rank: 44,
      name: "ZDF",
      type: "Media",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A media company's digital platform in Germany.",
    },
    {
      rank: 45,
      name: "PayPal",
      type: "Fintech",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+1.4%",
      changeValue: 1.4,
      description: "A leading online payment platform widely used for e-commerce in Germany.",
    },
    {
      rank: 46,
      name: "Klarna",
      type: "Fintech",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+3.2%",
      changeValue: 3.2,
      description: "A financial technology platform popular in Germany.",
    },
    {
      rank: 47,
      name: "N26",
      type: "Banking",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+5.5%",
      changeValue: 5.5,
      description: "A leading bank's online banking portal in Germany.",
    },
    {
      rank: 48,
      name: "Comdirect",
      type: "Banking",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A leading bank's online banking portal in Germany.",
    },
    {
      rank: 49,
      name: "Sparkasse",
      type: "Banking",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Germany.",
    },
    {
      rank: 50,
      name: "VR Bank",
      type: "Banking",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Germany.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Germany IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Germany.",
    "E-commerce is led by Amazon.de, Otto, Zalando, reflecting German shopping habits.",
    "Reddit shows the fastest growth at +5.8% month-over-month.",
    "News and media sites maintain strong daily traffic from German readers.",
    "Government and banking portals see steady usage across Germany.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Germany", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Germany in 2026?",
      answer: "In 2026, the most visited websites in Germany are led by Google, YouTube, Amazon.de, followed by Amazon.de and local platforms like eBay Kleinanzeigen, Bild, Spotify Germany. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Germany have in 2026?",
      answer: "Germany has over 78 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Germany?",
      answer: "Amazon.de is the most visited e-commerce site in Germany, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Germany?",
      answer: "Google is among the most visited websites in Germany. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Germany?",
      answer: "The top local websites in Germany include eBay Kleinanzeigen, Bild, Spotify Germany, which compete alongside global platforms for German users' attention.",
    },
    {
      question: "How is the traffic data for Germany websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Germany IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in France",
      href: "/most-visited-websites-in-france",
      description: "The 50 most visited websites in France, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
