import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-canada";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Canada [2026]",
  description: "Discover the 50 most visited websites in Canada in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.ca and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Canada [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Canada in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.ca and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Canada [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Canada in 2026, ranked by estimated monthly visits. See how Google, YouTube, Amazon.ca and more compare.",
  },
  robots: {
    index: false,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Canada",
  year: "2026",
  introduction: "Canada has over 38 million internet users, and its web traffic in 2026 reflects global platforms alongside local news and banking portals. This ranking lists the 50 most visited websites in Canada for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "4.2B",
      monthlyVisitsValue: 4200,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The leading search engine in Canada, handling the vast majority of Canadian web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "3.2B",
      monthlyVisitsValue: 3200,
      change: "+3.0%",
      changeValue: 3.0,
      description: "The dominant video platform in Canada for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Amazon.ca",
      type: "E-commerce",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+2.5%",
      changeValue: 2.5,
      description: "Amazon's Canadian storefront, a top online retailer in Canada.",
    },
    {
      rank: 4,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "-1.8%",
      changeValue: -1.8,
      description: "A major social networking platform widely used across Canada for community and news.",
    },
    {
      rank: 5,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+0.7%",
      changeValue: 0.7,
      description: "The free encyclopedia accessed heavily by Canadian students, researchers, and readers.",
    },
    {
      rank: 6,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "1.0B",
      monthlyVisitsValue: 1000,
      change: "+5.8%",
      changeValue: 5.8,
      description: "Community-driven forums growing fast among Canadian tech, finance, and gaming enthusiasts.",
    },
    {
      rank: 7,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "880M",
      monthlyVisitsValue: 880,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A fast-growing visual social platform popular among Canadian youth for reels and stories.",
    },
    {
      rank: 8,
      name: "X (Twitter)",
      type: "Social Network",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "-2.0%",
      changeValue: -2.0,
      description: "The real-time conversation platform widely used for news and politics in Canada.",
    },
    {
      rank: 9,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+2.2%",
      changeValue: 2.2,
      description: "A premium streaming service investing in Canadian original content.",
    },
    {
      rank: 10,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Canadian job seekers, recruiters, and B2B content.",
    },
    {
      rank: 11,
      name: "CBC",
      type: "Media",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A media company's digital platform in Canada.",
    },
    {
      rank: 12,
      name: "CTV",
      type: "Media",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in Canada.",
    },
    {
      rank: 13,
      name: "Global News",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Canadian and international headlines.",
    },
    {
      rank: 14,
      name: "Toronto Star",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering Canadian and international headlines.",
    },
    {
      rank: 15,
      name: "The Globe and Mail",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Canadian and international headlines.",
    },
    {
      rank: 16,
      name: "National Post",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A major news website covering Canadian and international headlines.",
    },
    {
      rank: 17,
      name: "Yahoo",
      type: "Portal",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "-1.5%",
      changeValue: -1.5,
      description: "A web portal offering news, search, and services in Canada.",
    },
    {
      rank: 18,
      name: "Bing",
      type: "Search Engine",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading search engine used by Canadian internet users for web queries.",
    },
    {
      rank: 19,
      name: "Weather Network",
      type: "Weather",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A weather forecast site widely used in Canada.",
    },
    {
      rank: 20,
      name: "Kijiji",
      type: "Classifieds",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A classifieds platform for buying and selling in Canada.",
    },
    {
      rank: 21,
      name: "Walmart Canada",
      type: "Retail",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 22,
      name: "Best Buy Canada",
      type: "Retail",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 23,
      name: "Canadian Tire",
      type: "Retail",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 24,
      name: "Indigo",
      type: "Retail",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 25,
      name: "Hudson's Bay",
      type: "Retail",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 26,
      name: "Sport Chek",
      type: "Retail",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 27,
      name: "Lululemon",
      type: "Retail",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 28,
      name: "Aritzia",
      type: "Retail",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+2.8%",
      changeValue: 2.8,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 29,
      name: "SSENSE",
      type: "Retail",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A retail brand's online store in Canada.",
    },
    {
      rank: 30,
      name: "Shopify",
      type: "Developer",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+5.5%",
      changeValue: 5.5,
      description: "A developer platform widely used by Canadian software engineers.",
    },
    {
      rank: 31,
      name: "Job Bank",
      type: "Job Portal",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A job search platform connecting Canadian professionals with employers.",
    },
    {
      rank: 32,
      name: "Indeed Canada",
      type: "Job Portal",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A job search platform connecting Canadian professionals with employers.",
    },
    {
      rank: 33,
      name: "Realtor.ca",
      type: "Real Estate",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+1.8%",
      changeValue: 1.8,
      description: "A property listing portal popular in Canada.",
    },
    {
      rank: 34,
      name: "Remax",
      type: "Real Estate",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A property listing portal popular in Canada.",
    },
    {
      rank: 35,
      name: "AutoTrader",
      type: "Automotive",
      monthlyVisits: "35M",
      monthlyVisitsValue: 35,
      change: "+1.2%",
      changeValue: 1.2,
      description: "An automotive marketplace for new and used cars in Canada.",
    },
    {
      rank: 36,
      name: "CIBC",
      type: "Banking",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A leading bank's online banking portal in Canada.",
    },
    {
      rank: 37,
      name: "RBC",
      type: "Banking",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Canada.",
    },
    {
      rank: 38,
      name: "TD",
      type: "Banking",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A leading bank's online banking portal in Canada.",
    },
    {
      rank: 39,
      name: "Scotiabank",
      type: "Banking",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Canada.",
    },
    {
      rank: 40,
      name: "BMO",
      type: "Banking",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Canada.",
    },
    {
      rank: 41,
      name: "Tangerine",
      type: "Banking",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading bank's online banking portal in Canada.",
    },
    {
      rank: 42,
      name: "Rogers",
      type: "Telecom",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A telecommunications provider's official site in Canada.",
    },
    {
      rank: 43,
      name: "Bell",
      type: "Telecom",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A telecommunications provider's official site in Canada.",
    },
    {
      rank: 44,
      name: "Telus",
      type: "Telecom",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A telecommunications provider's official site in Canada.",
    },
    {
      rank: 45,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A global accommodation booking platform widely used by Canadian travelers.",
    },
    {
      rank: 46,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 47,
      name: "Expedia",
      type: "Travel",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A travel booking platform widely used by Canadian travelers.",
    },
    {
      rank: 48,
      name: "Air Canada",
      type: "Travel",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Canadian travelers.",
    },
    {
      rank: 49,
      name: "PayPal",
      type: "Fintech",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading online payment platform widely used for e-commerce in Canada.",
    },
    {
      rank: 50,
      name: "ChatGPT / OpenAI",
      type: "AI Tool",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+15.0%",
      changeValue: 15.0,
      description: "The leading AI chatbot platform, experiencing explosive growth in Canada.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Canada IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Canada.",
    "E-commerce is led by Amazon.ca, reflecting Canadian shopping habits.",
    "ChatGPT / OpenAI shows the fastest growth at +15.0% month-over-month.",
    "News and media sites maintain strong daily traffic from Canadian readers.",
    "Government and banking portals see steady usage across Canada.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Canada", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Canada in 2026?",
      answer: "In 2026, the most visited websites in Canada are led by Google, YouTube, Amazon.ca, followed by Amazon.ca and local platforms like CBC, CTV, Global News. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Canada have in 2026?",
      answer: "Canada has over 38 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Canada?",
      answer: "Amazon.ca is the most visited e-commerce site in Canada, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Canada?",
      answer: "Google is among the most visited websites in Canada. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Canada?",
      answer: "The top local websites in Canada include CBC, CTV, Global News, which compete alongside global platforms for Canadian users' attention.",
    },
    {
      question: "How is the traffic data for Canada websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Canada IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
