import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-france";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in France [2026]",
  description: "Discover the 50 most visited websites in France in 2026, ranked by estimated monthly visits. See how Google, YouTube, Leboncoin and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in France [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in France in 2026, ranked by estimated monthly visits. See how Google, YouTube, Leboncoin and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in France [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in France in 2026, ranked by estimated monthly visits. See how Google, YouTube, Leboncoin and more compare.",
  },
  robots: {
    index: false,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "France",
  year: "2026",
  introduction: "France has over 65 million internet users, and its web traffic in 2026 reflects a blend of global giants and domestic champions like Leboncoin. This ranking lists the 50 most visited websites in France for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "5.5B",
      monthlyVisitsValue: 5500,
      change: "+1.2%",
      changeValue: 1.2,
      description: "The leading search engine in France, handling the vast majority of French web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "4.2B",
      monthlyVisitsValue: 4200,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The dominant video platform in France for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Leboncoin",
      type: "Classifieds",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "+2.5%",
      changeValue: 2.5,
      description: "France's leading classifieds platform for jobs, real estate, and goods.",
    },
    {
      rank: 4,
      name: "Amazon.fr",
      type: "E-commerce",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+2.6%",
      changeValue: 2.6,
      description: "Amazon's French storefront, a leading online retailer in France.",
    },
    {
      rank: 5,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "2.2B",
      monthlyVisitsValue: 2200,
      change: "-1.8%",
      changeValue: -1.8,
      description: "A major social networking platform widely used across France for community and news.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+0.6%",
      changeValue: 0.6,
      description: "The free encyclopedia accessed heavily by French students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Le Monde",
      type: "News",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 8,
      name: "Le Figaro",
      type: "News",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 9,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "880M",
      monthlyVisitsValue: 880,
      change: "+4.2%",
      changeValue: 4.2,
      description: "A fast-growing visual social platform popular among French youth for reels and stories.",
    },
    {
      rank: 10,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "750M",
      monthlyVisitsValue: 750,
      change: "-1.2%",
      changeValue: -1.2,
      description: "The real-time public conversation platform widely used for news in France.",
    },
    {
      rank: 11,
      name: "20 Minutes",
      type: "News",
      monthlyVisits: "680M",
      monthlyVisitsValue: 680,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 12,
      name: "BFMTV",
      type: "News",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+1.1%",
      changeValue: 1.1,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 13,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "550M",
      monthlyVisitsValue: 550,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A premium streaming service investing in French original content.",
    },
    {
      rank: 14,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "500M",
      monthlyVisitsValue: 500,
      change: "+2.5%",
      changeValue: 2.5,
      description: "The professional networking hub for French job seekers, recruiters, and B2B content.",
    },
    {
      rank: 15,
      name: "Cdiscount",
      type: "E-commerce",
      monthlyVisits: "450M",
      monthlyVisitsValue: 450,
      change: "+1.4%",
      changeValue: 1.4,
      description: "A popular online shopping destination in France for various products.",
    },
    {
      rank: 16,
      name: "Fnac",
      type: "Retail",
      monthlyVisits: "400M",
      monthlyVisitsValue: 400,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A retail brand's online store in France.",
    },
    {
      rank: 17,
      name: "Darty",
      type: "Retail",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A retail brand's online store in France.",
    },
    {
      rank: 18,
      name: "Carrefour",
      type: "Retail",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A retail brand's online store in France.",
    },
    {
      rank: 19,
      name: "Auchan",
      type: "Retail",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in France.",
    },
    {
      rank: 20,
      name: "Leclerc",
      type: "Retail",
      monthlyVisits: "290M",
      monthlyVisitsValue: 290,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in France.",
    },
    {
      rank: 21,
      name: "Orange",
      type: "Telecom",
      monthlyVisits: "260M",
      monthlyVisitsValue: 260,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A telecommunications provider's official site in France.",
    },
    {
      rank: 22,
      name: "SFR",
      type: "Telecom",
      monthlyVisits: "240M",
      monthlyVisitsValue: 240,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A telecommunications provider's official site in France.",
    },
    {
      rank: 23,
      name: "Bouygues",
      type: "Telecom",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A telecommunications provider's official site in France.",
    },
    {
      rank: 24,
      name: "Free",
      type: "Telecom",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A telecommunications provider's official site in France.",
    },
    {
      rank: 25,
      name: "BNP Paribas",
      type: "Banking",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+1.1%",
      changeValue: 1.1,
      description: "A leading bank's online banking portal in France.",
    },
    {
      rank: 26,
      name: "Credit Agricole",
      type: "Banking",
      monthlyVisits: "165M",
      monthlyVisitsValue: 165,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in France.",
    },
    {
      rank: 27,
      name: "Societe Generale",
      type: "Banking",
      monthlyVisits: "150M",
      monthlyVisitsValue: 150,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in France.",
    },
    {
      rank: 28,
      name: "La Banque Postale",
      type: "Banking",
      monthlyVisits: "135M",
      monthlyVisitsValue: 135,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A leading bank's online banking portal in France.",
    },
    {
      rank: 29,
      name: "RATP",
      type: "Travel",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+1.3%",
      changeValue: 1.3,
      description: "A travel booking platform widely used by French travelers.",
    },
    {
      rank: 30,
      name: "SNCF Connect",
      type: "Travel",
      monthlyVisits: "110M",
      monthlyVisitsValue: 110,
      change: "+2.1%",
      changeValue: 2.1,
      description: "A travel booking platform widely used by French travelers.",
    },
    {
      rank: 31,
      name: "Doctolib",
      type: "Health",
      monthlyVisits: "98M",
      monthlyVisitsValue: 98,
      change: "+4.5%",
      changeValue: 4.5,
      description: "A health information site accessed by French users.",
    },
    {
      rank: 32,
      name: "Vinted",
      type: "Marketplace",
      monthlyVisits: "88M",
      monthlyVisitsValue: 88,
      change: "+6.2%",
      changeValue: 6.2,
      description: "An online marketplace popular in France.",
    },
    {
      rank: 33,
      name: "Rakuten France",
      type: "E-commerce",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A popular online shopping destination in France for various products.",
    },
    {
      rank: 34,
      name: "6play",
      type: "Streaming",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+1.4%",
      changeValue: 1.4,
      description: "A streaming service popular among French viewers.",
    },
    {
      rank: 35,
      name: "M6",
      type: "Media",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in France.",
    },
    {
      rank: 36,
      name: "TF1",
      type: "Media",
      monthlyVisits: "60M",
      monthlyVisitsValue: 60,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A media company's digital platform in France.",
    },
    {
      rank: 37,
      name: "France.tv",
      type: "Media",
      monthlyVisits: "55M",
      monthlyVisitsValue: 55,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A media company's digital platform in France.",
    },
    {
      rank: 38,
      name: "Le Parisien",
      type: "News",
      monthlyVisits: "50M",
      monthlyVisitsValue: 50,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 39,
      name: "L'Equipe",
      type: "Sports",
      monthlyVisits: "45M",
      monthlyVisitsValue: 45,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A sports media site covering French and international sports.",
    },
    {
      rank: 40,
      name: "Ouest-France",
      type: "News",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 41,
      name: "Sud Ouest",
      type: "News",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 42,
      name: "La Depêche",
      type: "News",
      monthlyVisits: "35M",
      monthlyVisitsValue: 35,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 43,
      name: "Le Point",
      type: "News",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 44,
      name: "L'Express",
      type: "News",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "-0.1%",
      changeValue: -0.1,
      description: "A major news website covering French and international headlines.",
    },
    {
      rank: 45,
      name: "Elle",
      type: "Media",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A media company's digital platform in France.",
    },
    {
      rank: 46,
      name: "Marie Claire",
      type: "Media",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in France.",
    },
    {
      rank: 47,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+1.6%",
      changeValue: 1.6,
      description: "A global accommodation booking platform widely used by French travelers.",
    },
    {
      rank: 48,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 49,
      name: "Meetic",
      type: "Services",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A services platform widely used in France.",
    },
    {
      rank: 50,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+3.5%",
      changeValue: 3.5,
      description: "Community-driven forums growing fast among French tech, finance, and gaming enthusiasts.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from France IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in France.",
    "E-commerce is led by Amazon.fr, Cdiscount, Vinted, reflecting French shopping habits.",
    "Vinted shows the fastest growth at +6.2% month-over-month.",
    "News and media sites maintain strong daily traffic from French readers.",
    "Government and banking portals see steady usage across France.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in France", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in France in 2026?",
      answer: "In 2026, the most visited websites in France are led by Google, YouTube, Leboncoin, followed by Amazon.fr and local platforms like Le Monde, Le Figaro, 20 Minutes. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does France have in 2026?",
      answer: "France has over 65 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in France?",
      answer: "Amazon.fr is the most visited e-commerce site in France, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in France?",
      answer: "Google is among the most visited websites in France. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in France?",
      answer: "The top local websites in France include Le Monde, Le Figaro, 20 Minutes, which compete alongside global platforms for French users' attention.",
    },
    {
      question: "How is the traffic data for France websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of France IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
