import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-brazil";
const PAGE_URL = `https://trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Brazil [2026]",
  description: "Discover the 50 most visited websites in Brazil in 2026, ranked by estimated monthly visits. See how Google, YouTube, Globo and more compare.",
  metadataBase: new URL("https://trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Brazil [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Brazil in 2026, ranked by estimated monthly visits. See how Google, YouTube, Globo and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Brazil [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Brazil in 2026, ranked by estimated monthly visits. See how Google, YouTube, Globo and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Brazil",
  year: "2026",
  introduction: "Brazil has over 180 million internet users, and its web traffic in 2026 reflects global platforms alongside domestic leaders like Globo and Mercado Livre. This ranking lists the 50 most visited websites in Brazil for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "7.2B",
      monthlyVisitsValue: 7200,
      change: "+1.8%",
      changeValue: 1.8,
      description: "The leading search engine in Brazil, handling the vast majority of Brazilian web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "5.8B",
      monthlyVisitsValue: 5800,
      change: "+3.5%",
      changeValue: 3.5,
      description: "The dominant video platform in Brazil for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Globo",
      type: "Media",
      monthlyVisits: "3.5B",
      monthlyVisitsValue: 3500,
      change: "+1.2%",
      changeValue: 1.2,
      description: "Brazil's largest media conglomerate's web portal.",
    },
    {
      rank: 4,
      name: "UOL",
      type: "Portal",
      monthlyVisits: "2.2B",
      monthlyVisitsValue: 2200,
      change: "-0.8%",
      changeValue: -0.8,
      description: "A web portal offering news, search, and services in Brazil.",
    },
    {
      rank: 5,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "2.0B",
      monthlyVisitsValue: 2000,
      change: "-2.0%",
      changeValue: -2.0,
      description: "A major social networking platform widely used across Brazil for community and news.",
    },
    {
      rank: 6,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+5.2%",
      changeValue: 5.2,
      description: "A fast-growing visual social platform popular among Brazilian youth for reels and stories.",
    },
    {
      rank: 7,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+0.7%",
      changeValue: 0.7,
      description: "The free encyclopedia accessed heavily by Brazilian students, researchers, and readers.",
    },
    {
      rank: 8,
      name: "Mercado Livre",
      type: "E-commerce",
      monthlyVisits: "1.3B",
      monthlyVisitsValue: 1300,
      change: "+4.1%",
      changeValue: 4.1,
      description: "Latin America's largest e-commerce and fintech platform.",
    },
    {
      rank: 9,
      name: "Amazon Brazil",
      type: "E-commerce",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+3.0%",
      changeValue: 3.0,
      description: "Amazon's Brazilian storefront, competing with Mercado Livre.",
    },
    {
      rank: 10,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "-1.5%",
      changeValue: -1.5,
      description: "The real-time public conversation platform widely used for news in Brazil.",
    },
    {
      rank: 11,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Brazilian original content.",
    },
    {
      rank: 12,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "650M",
      monthlyVisitsValue: 650,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Brazilian job seekers, recruiters, and B2B content.",
    },
    {
      rank: 13,
      name: "G1",
      type: "News",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A major news website covering Brazilian and international headlines.",
    },
    {
      rank: 14,
      name: "Folha de S.Paulo",
      type: "News",
      monthlyVisits: "520M",
      monthlyVisitsValue: 520,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Brazilian and international headlines.",
    },
    {
      rank: 15,
      name: "Estadão",
      type: "News",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering Brazilian and international headlines.",
    },
    {
      rank: 16,
      name: "Veja",
      type: "News",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Brazilian and international headlines.",
    },
    {
      rank: 17,
      name: "Exame",
      type: "Business News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A business news publication in Brazil.",
    },
    {
      rank: 18,
      name: "Valor",
      type: "Business News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A business news publication in Brazil.",
    },
    {
      rank: 19,
      name: "Terra",
      type: "Portal",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "-1.0%",
      changeValue: -1.0,
      description: "A web portal offering news, search, and services in Brazil.",
    },
    {
      rank: 20,
      name: "Bol",
      type: "Portal",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A web portal offering news, search, and services in Brazil.",
    },
    {
      rank: 21,
      name: "iG",
      type: "Portal",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "-1.2%",
      changeValue: -1.2,
      description: "A web portal offering news, search, and services in Brazil.",
    },
    {
      rank: 22,
      name: "R7",
      type: "Portal",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "-0.8%",
      changeValue: -0.8,
      description: "A web portal offering news, search, and services in Brazil.",
    },
    {
      rank: 23,
      name: "Mercado Pago",
      type: "Fintech",
      monthlyVisits: "195M",
      monthlyVisitsValue: 195,
      change: "+5.5%",
      changeValue: 5.5,
      description: "A financial technology platform popular in Brazil.",
    },
    {
      rank: 24,
      name: "PicPay",
      type: "Fintech",
      monthlyVisits: "175M",
      monthlyVisitsValue: 175,
      change: "+3.8%",
      changeValue: 3.8,
      description: "A financial technology platform popular in Brazil.",
    },
    {
      rank: 25,
      name: "Nubank",
      type: "Banking",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+6.2%",
      changeValue: 6.2,
      description: "A leading bank's online banking portal in Brazil.",
    },
    {
      rank: 26,
      name: "Itaú",
      type: "Banking",
      monthlyVisits: "145M",
      monthlyVisitsValue: 145,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading bank's online banking portal in Brazil.",
    },
    {
      rank: 27,
      name: "Bradesco",
      type: "Banking",
      monthlyVisits: "130M",
      monthlyVisitsValue: 130,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Brazil.",
    },
    {
      rank: 28,
      name: "Banco do Brasil",
      type: "Banking",
      monthlyVisits: "115M",
      monthlyVisitsValue: 115,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Brazil.",
    },
    {
      rank: 29,
      name: "Caixa",
      type: "Banking",
      monthlyVisits: "100M",
      monthlyVisitsValue: 100,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A leading bank's online banking portal in Brazil.",
    },
    {
      rank: 30,
      name: "Santander Brazil",
      type: "Banking",
      monthlyVisits: "88M",
      monthlyVisitsValue: 88,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A leading bank's online banking portal in Brazil.",
    },
    {
      rank: 31,
      name: "Magalu",
      type: "E-commerce",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A popular online shopping destination in Brazil for various products.",
    },
    {
      rank: 32,
      name: "Americanas",
      type: "E-commerce",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A popular online shopping destination in Brazil for various products.",
    },
    {
      rank: 33,
      name: "Submarino",
      type: "E-commerce",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "-1.0%",
      changeValue: -1.0,
      description: "A popular online shopping destination in Brazil for various products.",
    },
    {
      rank: 34,
      name: "Shoptime",
      type: "E-commerce",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "-0.8%",
      changeValue: -0.8,
      description: "A popular online shopping destination in Brazil for various products.",
    },
    {
      rank: 35,
      name: "Casas Bahia",
      type: "Retail",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A retail brand's online store in Brazil.",
    },
    {
      rank: 36,
      name: "Ponto Frio",
      type: "Retail",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A retail brand's online store in Brazil.",
    },
    {
      rank: 37,
      name: "Extra",
      type: "Retail",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A retail brand's online store in Brazil.",
    },
    {
      rank: 38,
      name: "Carrefour Brazil",
      type: "Retail",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A retail brand's online store in Brazil.",
    },
    {
      rank: 39,
      name: "WhatsApp",
      type: "Messaging",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A leading messaging app whose web client is accessed by millions in Brazil.",
    },
    {
      rank: 40,
      name: "Telegram",
      type: "Messaging",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A messaging platform whose web client is used in Brazil.",
    },
    {
      rank: 41,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+4.5%",
      changeValue: 4.5,
      description: "Community-driven forums growing fast among Brazilian tech, finance, and gaming enthusiasts.",
    },
    {
      rank: 42,
      name: "Spotify Brazil",
      type: "Music",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+3.0%",
      changeValue: 3.0,
      description: "A music streaming service popular in Brazil.",
    },
    {
      rank: 43,
      name: "Deezer",
      type: "Music",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A music streaming service popular in Brazil.",
    },
    {
      rank: 44,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A global accommodation booking platform widely used by Brazilian travelers.",
    },
    {
      rank: 45,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 46,
      name: "Decolar",
      type: "Travel",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A travel booking platform widely used by Brazilian travelers.",
    },
    {
      rank: 47,
      name: "Kabum",
      type: "E-commerce",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+3.2%",
      changeValue: 3.2,
      description: "A popular online shopping destination in Brazil for various products.",
    },
    {
      rank: 48,
      name: "Hotmail",
      type: "Email",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "-0.5%",
      changeValue: -0.5,
      description: "An email service widely used in Brazil.",
    },
    {
      rank: 49,
      name: "Gmail",
      type: "Email",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+1.0%",
      changeValue: 1.0,
      description: "An email service widely used in Brazil.",
    },
    {
      rank: 50,
      name: "Pinterest",
      type: "Social Network",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A visual discovery platform popular for fashion, decor, and recipe inspiration.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Brazil IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Brazil.",
    "E-commerce is led by Mercado Livre, Amazon Brazil, Magalu, reflecting Brazilian shopping habits.",
    "Nubank shows the fastest growth at +6.2% month-over-month.",
    "News and media sites maintain strong daily traffic from Brazilian readers.",
    "Government and banking portals see steady usage across Brazil.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Brazil", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Brazil in 2026?",
      answer: "In 2026, the most visited websites in Brazil are led by Google, YouTube, Globo, followed by Mercado Livre and local platforms like UOL, G1, Folha de S.Paulo. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Brazil have in 2026?",
      answer: "Brazil has over 180 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Brazil?",
      answer: "Mercado Livre is the most visited e-commerce site in Brazil, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Brazil?",
      answer: "Google is among the most visited websites in Brazil. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Brazil?",
      answer: "The top local websites in Brazil include UOL, G1, Folha de S.Paulo, which compete alongside global platforms for Brazilian users' attention.",
    },
    {
      question: "How is the traffic data for Brazil websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Brazil IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
