import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-south-korea";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in South Korea [2026]",
  description: "Discover the 50 most visited websites in South Korea in 2026, ranked by estimated monthly visits. See how Naver, Daum, YouTube and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in South Korea [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in South Korea in 2026, ranked by estimated monthly visits. See how Naver, Daum, YouTube and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in South Korea [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in South Korea in 2026, ranked by estimated monthly visits. See how Naver, Daum, YouTube and more compare.",
  },
  robots: {
    index: false,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "South Korea",
  year: "2026",
  introduction: "South Korea has over 50 million internet users, and its web traffic in 2026 reflects unique local platforms like Naver and Kakao dominating the market. This ranking lists the 50 most visited websites in South Korea for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Naver",
      type: "Search Engine",
      monthlyVisits: "4.2B",
      monthlyVisitsValue: 4200,
      change: "+1.5%",
      changeValue: 1.5,
      description: "South Korea's dominant search portal and web platform.",
    },
    {
      rank: 2,
      name: "Daum",
      type: "Portal",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A major Korean web portal and search engine, now part of Kakao.",
    },
    {
      rank: 3,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+4.2%",
      changeValue: 4.2,
      description: "The dominant video platform in South Korea for entertainment, music, and education.",
    },
    {
      rank: 4,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "2.2B",
      monthlyVisitsValue: 2200,
      change: "+1.0%",
      changeValue: 1.0,
      description: "The leading search engine in South Korea, handling the vast majority of Korean web queries.",
    },
    {
      rank: 5,
      name: "Namuwiki",
      type: "Reference",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+8.5%",
      changeValue: 8.5,
      description: "A reference website widely used in South Korea.",
    },
    {
      rank: 6,
      name: "Coupang",
      type: "E-commerce",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+5.5%",
      changeValue: 5.5,
      description: "South Korea's largest e-commerce platform, known for ultra-fast delivery.",
    },
    {
      rank: 7,
      name: "11st",
      type: "E-commerce",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 8,
      name: "Gmarket",
      type: "E-commerce",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 9,
      name: "Auction",
      type: "E-commerce",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 10,
      name: "SSG",
      type: "E-commerce",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 11,
      name: "TMON",
      type: "E-commerce",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 12,
      name: "Wemakeprice",
      type: "E-commerce",
      monthlyVisits: "520M",
      monthlyVisitsValue: 520,
      change: "-1.0%",
      changeValue: -1.0,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 13,
      name: "Interpark",
      type: "E-commerce",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A popular online shopping destination in South Korea for various products.",
    },
    {
      rank: 14,
      name: "Yes24",
      type: "Retail",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A retail brand's online store in South Korea.",
    },
    {
      rank: 15,
      name: "Kyobo",
      type: "Retail",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in South Korea.",
    },
    {
      rank: 16,
      name: "Bunjang",
      type: "Marketplace",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+3.2%",
      changeValue: 3.2,
      description: "An online marketplace popular in South Korea.",
    },
    {
      rank: 17,
      name: "Joongna",
      type: "Marketplace",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+4.5%",
      changeValue: 4.5,
      description: "An online marketplace popular in South Korea.",
    },
    {
      rank: 18,
      name: "Karrot",
      type: "Marketplace",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+7.5%",
      changeValue: 7.5,
      description: "An online marketplace popular in South Korea.",
    },
    {
      rank: 19,
      name: "DC Inside",
      type: "Forum",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A popular forum website in South Korea.",
    },
    {
      rank: 20,
      name: "Theqoo",
      type: "Social Forum",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+2.5%",
      changeValue: 2.5,
      description: "Community-driven forums popular among Korean internet users.",
    },
    {
      rank: 21,
      name: "Naver Cafe",
      type: "Social Forum",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+1.5%",
      changeValue: 1.5,
      description: "Community-driven forums popular among Korean internet users.",
    },
    {
      rank: 22,
      name: "Naver Blog",
      type: "Blog",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A blogging platform popular among Korean writers and readers.",
    },
    {
      rank: 23,
      name: "Tistory",
      type: "Blog",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A blogging platform popular among Korean writers and readers.",
    },
    {
      rank: 24,
      name: "Hankyung",
      type: "Business News",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A business news publication in South Korea.",
    },
    {
      rank: 25,
      name: "Chosun",
      type: "News",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Korean and international headlines.",
    },
    {
      rank: 26,
      name: "Donga",
      type: "News",
      monthlyVisits: "110M",
      monthlyVisitsValue: 110,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Korean and international headlines.",
    },
    {
      rank: 27,
      name: "Joongang",
      type: "News",
      monthlyVisits: "98M",
      monthlyVisitsValue: 98,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Korean and international headlines.",
    },
    {
      rank: 28,
      name: "MK Sports",
      type: "Sports",
      monthlyVisits: "88M",
      monthlyVisitsValue: 88,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A sports media site covering Korean and international sports.",
    },
    {
      rank: 29,
      name: "Sports Seoul",
      type: "Sports",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A sports media site covering Korean and international sports.",
    },
    {
      rank: 30,
      name: "Sports Donga",
      type: "Sports",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A sports media site covering Korean and international sports.",
    },
    {
      rank: 31,
      name: "Ilgan Sports",
      type: "Sports",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A sports media site covering Korean and international sports.",
    },
    {
      rank: 32,
      name: "OSEN",
      type: "Sports",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A sports media site covering Korean and international sports.",
    },
    {
      rank: 33,
      name: "Nate",
      type: "Portal",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "-1.5%",
      changeValue: -1.5,
      description: "A web portal offering news, search, and services in South Korea.",
    },
    {
      rank: 34,
      name: "Zum",
      type: "Portal",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A web portal offering news, search, and services in South Korea.",
    },
    {
      rank: 35,
      name: "KBS",
      type: "Media",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in South Korea.",
    },
    {
      rank: 36,
      name: "MBC",
      type: "Media",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in South Korea.",
    },
    {
      rank: 37,
      name: "SBS",
      type: "Media",
      monthlyVisits: "35M",
      monthlyVisitsValue: 35,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A media company's digital platform in South Korea.",
    },
    {
      rank: 38,
      name: "JTBC",
      type: "Media",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A media company's digital platform in South Korea.",
    },
    {
      rank: 39,
      name: "TVN",
      type: "Media",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A media company's digital platform in South Korea.",
    },
    {
      rank: 40,
      name: "OCN",
      type: "Media",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in South Korea.",
    },
    {
      rank: 41,
      name: "Megabox",
      type: "Entertainment",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+1.8%",
      changeValue: 1.8,
      description: "An entertainment platform popular in South Korea.",
    },
    {
      rank: 42,
      name: "CGV",
      type: "Entertainment",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+1.2%",
      changeValue: 1.2,
      description: "An entertainment platform popular in South Korea.",
    },
    {
      rank: 43,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "-2.5%",
      changeValue: -2.5,
      description: "A major social networking platform widely used across South Korea for community and news.",
    },
    {
      rank: 44,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A fast-growing visual social platform popular among Korean youth for reels and stories.",
    },
    {
      rank: 45,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Korean original content.",
    },
    {
      rank: 46,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "-1.0%",
      changeValue: -1.0,
      description: "The real-time public conversation platform widely used for news in South Korea.",
    },
    {
      rank: 47,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Korean students, researchers, and readers.",
    },
    {
      rank: 48,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+2.0%",
      changeValue: 2.0,
      description: "The professional networking hub for Korean job seekers, recruiters, and B2B content.",
    },
    {
      rank: 49,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+3.5%",
      changeValue: 3.5,
      description: "Community-driven forums growing fast among Korean tech, finance, and gaming enthusiasts.",
    },
    {
      rank: 50,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A global accommodation booking platform widely used by Korean travelers.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from South Korea IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Naver tops the list as the most visited website in South Korea.",
    "E-commerce is led by Coupang, 11st, Gmarket, reflecting Korean shopping habits.",
    "Namuwiki shows the fastest growth at +8.5% month-over-month.",
    "News and media sites maintain strong daily traffic from Korean readers.",
    "Government and banking portals see steady usage across South Korea.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in South Korea", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in South Korea in 2026?",
      answer: "In 2026, the most visited websites in South Korea are led by Naver, Daum, YouTube, followed by Coupang and local platforms like Namuwiki, 11st, Gmarket. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does South Korea have in 2026?",
      answer: "South Korea has over 50 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in South Korea?",
      answer: "Coupang is the most visited e-commerce site in South Korea, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in South Korea?",
      answer: "Google is among the most visited websites in South Korea. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in South Korea?",
      answer: "The top local websites in South Korea include Namuwiki, 11st, Gmarket, which compete alongside global platforms for Korean users' attention.",
    },
    {
      question: "How is the traffic data for South Korea websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of South Korea IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
