import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-indonesia";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Indonesia [2026]",
  description: "Discover the 50 most visited websites in Indonesia in 2026, ranked by estimated monthly visits. See how Google, YouTube, Tokopedia and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Indonesia [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Indonesia in 2026, ranked by estimated monthly visits. See how Google, YouTube, Tokopedia and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Indonesia [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Indonesia in 2026, ranked by estimated monthly visits. See how Google, YouTube, Tokopedia and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Indonesia",
  year: "2026",
  introduction: "Indonesia has over 220 million internet users, and its web traffic in 2026 reflects a vibrant mix of global platforms and local e-commerce giants. This ranking lists the 50 most visited websites in Indonesia for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "5.8B",
      monthlyVisitsValue: 5800,
      change: "+1.8%",
      changeValue: 1.8,
      description: "The leading search engine in Indonesia, handling the vast majority of Indonesian web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "4.5B",
      monthlyVisitsValue: 4500,
      change: "+3.5%",
      changeValue: 3.5,
      description: "The dominant video platform in Indonesia for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Tokopedia",
      type: "E-commerce",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "+2.5%",
      changeValue: 2.5,
      description: "Indonesia's leading online marketplace for goods and services.",
    },
    {
      rank: 4,
      name: "Shopee",
      type: "E-commerce",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+5.0%",
      changeValue: 5.0,
      description: "A fast-growing e-commerce platform dominant in Southeast Asia.",
    },
    {
      rank: 5,
      name: "Bukalapak",
      type: "E-commerce",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "-1.5%",
      changeValue: -1.5,
      description: "A popular online shopping destination in Indonesia for various products.",
    },
    {
      rank: 6,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "1.0B",
      monthlyVisitsValue: 1000,
      change: "-2.0%",
      changeValue: -2.0,
      description: "A major social networking platform widely used across Indonesia for community and news.",
    },
    {
      rank: 7,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "880M",
      monthlyVisitsValue: 880,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Indonesian students, researchers, and readers.",
    },
    {
      rank: 8,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+4.2%",
      changeValue: 4.2,
      description: "A fast-growing visual social platform popular among Indonesian youth for reels and stories.",
    },
    {
      rank: 9,
      name: "Detik",
      type: "News",
      monthlyVisits: "680M",
      monthlyVisitsValue: 680,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 10,
      name: "Kompas",
      type: "News",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 11,
      name: "Tribunnews",
      type: "News",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 12,
      name: "Liputan6",
      type: "News",
      monthlyVisits: "520M",
      monthlyVisitsValue: 520,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 13,
      name: "Kapanlagi",
      type: "Entertainment",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+0.4%",
      changeValue: 0.4,
      description: "An entertainment platform popular in Indonesia.",
    },
    {
      rank: 14,
      name: "Merdeka",
      type: "News",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 15,
      name: "SINDO",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "-0.5%",
      changeValue: -0.5,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 16,
      name: "CNN Indonesia",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 17,
      name: "CNBC Indonesia",
      type: "Business News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A business news publication in Indonesia.",
    },
    {
      rank: 18,
      name: "Tempo",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Indonesian and international headlines.",
    },
    {
      rank: 19,
      name: "Kontan",
      type: "Business News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A business news publication in Indonesia.",
    },
    {
      rank: 20,
      name: "Bisnis Indonesia",
      type: "Business News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A business news publication in Indonesia.",
    },
    {
      rank: 21,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "-1.5%",
      changeValue: -1.5,
      description: "The real-time public conversation platform widely used for news in Indonesia.",
    },
    {
      rank: 22,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Indonesian original content.",
    },
    {
      rank: 23,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Indonesian job seekers, recruiters, and B2B content.",
    },
    {
      rank: 24,
      name: "JNE",
      type: "Services",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A services platform widely used in Indonesia.",
    },
    {
      rank: 25,
      name: "J&T",
      type: "Services",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A services platform widely used in Indonesia.",
    },
    {
      rank: 26,
      name: "SiCepat",
      type: "Services",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+2.8%",
      changeValue: 2.8,
      description: "A services platform widely used in Indonesia.",
    },
    {
      rank: 27,
      name: "AnterAja",
      type: "Services",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+2.2%",
      changeValue: 2.2,
      description: "A services platform widely used in Indonesia.",
    },
    {
      rank: 28,
      name: "BCA",
      type: "Banking",
      monthlyVisits: "88M",
      monthlyVisitsValue: 88,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading bank's online banking portal in Indonesia.",
    },
    {
      rank: 29,
      name: "Mandiri",
      type: "Banking",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Indonesia.",
    },
    {
      rank: 30,
      name: "BRI",
      type: "Banking",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Indonesia.",
    },
    {
      rank: 31,
      name: "BNI",
      type: "Banking",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A leading bank's online banking portal in Indonesia.",
    },
    {
      rank: 32,
      name: "CIMB Niaga",
      type: "Banking",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Indonesia.",
    },
    {
      rank: 33,
      name: "Permata",
      type: "Banking",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Indonesia.",
    },
    {
      rank: 34,
      name: "GoPay",
      type: "Fintech",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A financial technology platform popular in Indonesia.",
    },
    {
      rank: 35,
      name: "OVO",
      type: "Fintech",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+2.8%",
      changeValue: 2.8,
      description: "A financial technology platform popular in Indonesia.",
    },
    {
      rank: 36,
      name: "Dana",
      type: "Fintech",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A financial technology platform popular in Indonesia.",
    },
    {
      rank: 37,
      name: "LinkAja",
      type: "Fintech",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A financial technology platform popular in Indonesia.",
    },
    {
      rank: 38,
      name: "Traveloka",
      type: "Travel",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A travel booking platform widely used by Indonesian travelers.",
    },
    {
      rank: 39,
      name: "Tiket.com",
      type: "Travel",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+1.8%",
      changeValue: 1.8,
      description: "A travel booking platform widely used by Indonesian travelers.",
    },
    {
      rank: 40,
      name: "Pegipegi",
      type: "Travel",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A travel booking platform widely used by Indonesian travelers.",
    },
    {
      rank: 41,
      name: "Blibli",
      type: "E-commerce",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A popular online shopping destination in Indonesia for various products.",
    },
    {
      rank: 42,
      name: "Lazada",
      type: "E-commerce",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A popular online shopping destination in Indonesia for various products.",
    },
    {
      rank: 43,
      name: "Zalora",
      type: "E-commerce",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A popular online shopping destination in Indonesia for various products.",
    },
    {
      rank: 44,
      name: "Sociolla",
      type: "Retail",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A retail brand's online store in Indonesia.",
    },
    {
      rank: 45,
      name: "Orami",
      type: "Retail",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Indonesia.",
    },
    {
      rank: 46,
      name: "IDN Media",
      type: "Media",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A media company's digital platform in Indonesia.",
    },
    {
      rank: 47,
      name: "RCTI",
      type: "Media",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Indonesia.",
    },
    {
      rank: 48,
      name: "MNCTV",
      type: "Media",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Indonesia.",
    },
    {
      rank: 49,
      name: "GTV",
      type: "Media",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in Indonesia.",
    },
    {
      rank: 50,
      name: "iNews",
      type: "Media",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A media company's digital platform in Indonesia.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Indonesia IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Indonesia.",
    "E-commerce is led by Tokopedia, Shopee, Bukalapak, reflecting Indonesian shopping habits.",
    "Shopee shows the fastest growth at +5.0% month-over-month.",
    "News and media sites maintain strong daily traffic from Indonesian readers.",
    "Government and banking portals see steady usage across Indonesia.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Indonesia", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Indonesia in 2026?",
      answer: "In 2026, the most visited websites in Indonesia are led by Google, YouTube, Tokopedia, followed by Tokopedia and local platforms like Bukalapak, Detik, Kompas. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Indonesia have in 2026?",
      answer: "Indonesia has over 220 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Indonesia?",
      answer: "Tokopedia is the most visited e-commerce site in Indonesia, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Indonesia?",
      answer: "Google is among the most visited websites in Indonesia. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Indonesia?",
      answer: "The top local websites in Indonesia include Bukalapak, Detik, Kompas, which compete alongside global platforms for Indonesian users' attention.",
    },
    {
      question: "How is the traffic data for Indonesia websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Indonesia IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
