import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-united-kingdom";
const PAGE_URL = `https://trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in United Kingdom [2026]",
  description: "Discover the 50 most visited websites in United Kingdom in 2026, ranked by estimated monthly visits. See how Google UK, YouTube, BBC and more compare.",
  metadataBase: new URL("https://trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in United Kingdom [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in United Kingdom in 2026, ranked by estimated monthly visits. See how Google UK, YouTube, BBC and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in United Kingdom [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in United Kingdom in 2026, ranked by estimated monthly visits. See how Google UK, YouTube, BBC and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "United Kingdom",
  year: "2026",
  introduction: "United Kingdom has over 65 million internet users, and its web traffic in 2026 reflects the BBC's trusted news to Amazon UK's delivery dominance. This ranking lists the 50 most visited websites in United Kingdom for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google UK",
      type: "Search Engine",
      monthlyVisits: "8.5B",
      monthlyVisitsValue: 8500,
      change: "+1.8%",
      changeValue: 1.8,
      description: "A leading search engine used by British internet users for web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "6.2B",
      monthlyVisitsValue: 6200,
      change: "+3.2%",
      changeValue: 3.2,
      description: "The dominant video platform in United Kingdom for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "BBC",
      type: "Media",
      monthlyVisits: "3.8B",
      monthlyVisitsValue: 3800,
      change: "+1.2%",
      changeValue: 1.2,
      description: "The BBC's online presence, offering news, iPlayer, sport, and weather.",
    },
    {
      rank: 4,
      name: "Amazon UK",
      type: "E-commerce",
      monthlyVisits: "3.2B",
      monthlyVisitsValue: 3200,
      change: "+2.9%",
      changeValue: 2.9,
      description: "Amazon's UK storefront leading electronics, books, and Prime delivery.",
    },
    {
      rank: 5,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "2.8B",
      monthlyVisitsValue: 2800,
      change: "-1.8%",
      changeValue: -1.8,
      description: "A major social networking platform widely used across United Kingdom for community and news.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+0.7%",
      changeValue: 0.7,
      description: "The free encyclopedia accessed heavily by British students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Reddit",
      type: "Social Forum",
      monthlyVisits: "2.1B",
      monthlyVisitsValue: 2100,
      change: "+6.5%",
      changeValue: 6.5,
      description: "Community-driven forums growing fast among British tech, finance, and gaming enthusiasts.",
    },
    {
      rank: 8,
      name: "eBay UK",
      type: "Marketplace",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "-0.5%",
      changeValue: -0.5,
      description: "An online marketplace popular in United Kingdom.",
    },
    {
      rank: 9,
      name: "Mail Online",
      type: "News",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "-1.0%",
      changeValue: -1.0,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 10,
      name: "The Guardian",
      type: "News",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+2.1%",
      changeValue: 2.1,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 11,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "1.1B",
      monthlyVisitsValue: 1100,
      change: "+4.8%",
      changeValue: 4.8,
      description: "A fast-growing visual social platform popular among British youth for reels and stories.",
    },
    {
      rank: 12,
      name: "X (Twitter)",
      type: "Social Network",
      monthlyVisits: "950M",
      monthlyVisitsValue: 950,
      change: "-2.3%",
      changeValue: -2.3,
      description: "The real-time conversation platform widely used for news and politics in United Kingdom.",
    },
    {
      rank: 13,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "820M",
      monthlyVisitsValue: 820,
      change: "+2.6%",
      changeValue: 2.6,
      description: "A premium streaming service investing in British original content.",
    },
    {
      rank: 14,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+3.1%",
      changeValue: 3.1,
      description: "The professional networking hub for British job seekers, recruiters, and B2B content.",
    },
    {
      rank: 15,
      name: "BBC News",
      type: "News",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 16,
      name: "GOV.UK",
      type: "Government",
      monthlyVisits: "680M",
      monthlyVisitsValue: 680,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The UK government's official portal for services and information.",
    },
    {
      rank: 17,
      name: "Rightmove",
      type: "Real Estate",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+2.8%",
      changeValue: 2.8,
      description: "A property listing portal popular in United Kingdom.",
    },
    {
      rank: 18,
      name: "Argos",
      type: "Retail",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+1.3%",
      changeValue: 1.3,
      description: "A retail brand's online store in United Kingdom.",
    },
    {
      rank: 19,
      name: "Tesco",
      type: "Retail",
      monthlyVisits: "540M",
      monthlyVisitsValue: 540,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A retail brand's online store in United Kingdom.",
    },
    {
      rank: 20,
      name: "Asda",
      type: "Retail",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+1.1%",
      changeValue: 1.1,
      description: "A retail brand's online store in United Kingdom.",
    },
    {
      rank: 21,
      name: "Gumtree",
      type: "Classifieds",
      monthlyVisits: "440M",
      monthlyVisitsValue: 440,
      change: "-1.2%",
      changeValue: -1.2,
      description: "A classifieds platform for buying and selling in United Kingdom.",
    },
    {
      rank: 22,
      name: "Autotrader",
      type: "Automotive",
      monthlyVisits: "400M",
      monthlyVisitsValue: 400,
      change: "+1.6%",
      changeValue: 1.6,
      description: "An automotive marketplace for new and used cars in United Kingdom.",
    },
    {
      rank: 23,
      name: "National Rail",
      type: "Travel",
      monthlyVisits: "370M",
      monthlyVisitsValue: 370,
      change: "+2.4%",
      changeValue: 2.4,
      description: "A travel booking platform widely used by British travelers.",
    },
    {
      rank: 24,
      name: "Sky Sports",
      type: "Sports",
      monthlyVisits: "340M",
      monthlyVisitsValue: 340,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A sports media site covering British and international sports.",
    },
    {
      rank: 25,
      name: "BT",
      type: "Telecom",
      monthlyVisits: "310M",
      monthlyVisitsValue: 310,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A telecommunications provider's official site in United Kingdom.",
    },
    {
      rank: 26,
      name: "The Telegraph",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "-0.3%",
      changeValue: -0.3,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 27,
      name: "The Sun",
      type: "News",
      monthlyVisits: "260M",
      monthlyVisitsValue: 260,
      change: "-0.8%",
      changeValue: -0.8,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 28,
      name: "Metro",
      type: "News",
      monthlyVisits: "240M",
      monthlyVisitsValue: 240,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 29,
      name: "Mirror",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "-0.6%",
      changeValue: -0.6,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 30,
      name: "Independent",
      type: "News",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+1.4%",
      changeValue: 1.4,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 31,
      name: "Express",
      type: "News",
      monthlyVisits: "185M",
      monthlyVisitsValue: 185,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 32,
      name: "Daily Mail",
      type: "News",
      monthlyVisits: "170M",
      monthlyVisitsValue: 170,
      change: "-0.9%",
      changeValue: -0.9,
      description: "A major news website covering British and international headlines.",
    },
    {
      rank: 33,
      name: "John Lewis",
      type: "Retail",
      monthlyVisits: "155M",
      monthlyVisitsValue: 155,
      change: "+1.7%",
      changeValue: 1.7,
      description: "A retail brand's online store in United Kingdom.",
    },
    {
      rank: 34,
      name: "Marks & Spencer",
      type: "Retail",
      monthlyVisits: "145M",
      monthlyVisitsValue: 145,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A retail brand's online store in United Kingdom.",
    },
    {
      rank: 35,
      name: "Currys",
      type: "Retail",
      monthlyVisits: "135M",
      monthlyVisitsValue: 135,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A retail brand's online store in United Kingdom.",
    },
    {
      rank: 36,
      name: "Halfords",
      type: "Automotive",
      monthlyVisits: "125M",
      monthlyVisitsValue: 125,
      change: "+1.0%",
      changeValue: 1.0,
      description: "An automotive marketplace for new and used cars in United Kingdom.",
    },
    {
      rank: 37,
      name: "Zoopla",
      type: "Real Estate",
      monthlyVisits: "115M",
      monthlyVisitsValue: 115,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A property listing portal popular in United Kingdom.",
    },
    {
      rank: 38,
      name: "Saga",
      type: "Services",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A services platform widely used in United Kingdom.",
    },
    {
      rank: 39,
      name: "NHS",
      type: "Health",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+2.2%",
      changeValue: 2.2,
      description: "A health information site accessed by British users.",
    },
    {
      rank: 40,
      name: "HMRC",
      type: "Government",
      monthlyVisits: "88M",
      monthlyVisitsValue: 88,
      change: "+0.7%",
      changeValue: 0.7,
      description: "An official government service portal in United Kingdom.",
    },
    {
      rank: 41,
      name: "DVLA",
      type: "Government",
      monthlyVisits: "82M",
      monthlyVisitsValue: 82,
      change: "+0.6%",
      changeValue: 0.6,
      description: "An official government service portal in United Kingdom.",
    },
    {
      rank: 42,
      name: "Royal Mail",
      type: "Services",
      monthlyVisits: "75M",
      monthlyVisitsValue: 75,
      change: "+1.1%",
      changeValue: 1.1,
      description: "A services platform widely used in United Kingdom.",
    },
    {
      rank: 43,
      name: "Post Office",
      type: "Services",
      monthlyVisits: "68M",
      monthlyVisitsValue: 68,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A services platform widely used in United Kingdom.",
    },
    {
      rank: 44,
      name: "Lloyds Bank",
      type: "Banking",
      monthlyVisits: "62M",
      monthlyVisitsValue: 62,
      change: "+1.3%",
      changeValue: 1.3,
      description: "A leading bank's online banking portal in United Kingdom.",
    },
    {
      rank: 45,
      name: "Barclays",
      type: "Banking",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.9%",
      changeValue: 0.9,
      description: "A leading bank's online banking portal in United Kingdom.",
    },
    {
      rank: 46,
      name: "NatWest",
      type: "Banking",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A leading bank's online banking portal in United Kingdom.",
    },
    {
      rank: 47,
      name: "HSBC",
      type: "Banking",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A leading bank's online banking portal in United Kingdom.",
    },
    {
      rank: 48,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+1.8%",
      changeValue: 1.8,
      description: "A global accommodation booking platform widely used by British travelers.",
    },
    {
      rank: 49,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "-0.4%",
      changeValue: -0.4,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 50,
      name: "Trainline",
      type: "Travel",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+3.5%",
      changeValue: 3.5,
      description: "A travel booking platform widely used by British travelers.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from United Kingdom IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google UK tops the list as the most visited website in United Kingdom.",
    "E-commerce is led by Amazon UK, eBay UK, reflecting British shopping habits.",
    "Reddit shows the fastest growth at +6.5% month-over-month.",
    "News and media sites maintain strong daily traffic from British readers.",
    "Government and banking portals see steady usage across United Kingdom.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in United Kingdom", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in United Kingdom in 2026?",
      answer: "In 2026, the most visited websites in United Kingdom are led by Google UK, YouTube, BBC, followed by Amazon UK and local platforms like Google UK, eBay UK, Mail Online. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does United Kingdom have in 2026?",
      answer: "United Kingdom has over 65 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in United Kingdom?",
      answer: "Amazon UK is the most visited e-commerce site in United Kingdom, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in United Kingdom?",
      answer: "Google is among the most visited websites in United Kingdom. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in United Kingdom?",
      answer: "The top local websites in United Kingdom include Google UK, eBay UK, Mail Online, which compete alongside global platforms for British users' attention.",
    },
    {
      question: "How is the traffic data for United Kingdom websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of United Kingdom IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in France",
      href: "/most-visited-websites-in-france",
      description: "The 50 most visited websites in France, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
