import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-vietnam";
const PAGE_URL = `https://trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Vietnam [2026]",
  description: "Discover the 50 most visited websites in Vietnam in 2026, ranked by estimated monthly visits. See how Google, YouTube, Shopee and more compare.",
  metadataBase: new URL("https://trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Vietnam [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Vietnam in 2026, ranked by estimated monthly visits. See how Google, YouTube, Shopee and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Vietnam [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Vietnam in 2026, ranked by estimated monthly visits. See how Google, YouTube, Shopee and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Vietnam",
  year: "2026",
  introduction: "Vietnam has over 80 million internet users, and its web traffic in 2026 reflects global platforms alongside local news and e-commerce giants. This ranking lists the 50 most visited websites in Vietnam for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "2.5B",
      monthlyVisitsValue: 2500,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The leading search engine in Vietnam, handling the vast majority of Vietnamese web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "2.0B",
      monthlyVisitsValue: 2000,
      change: "+3.2%",
      changeValue: 3.2,
      description: "The dominant video platform in Vietnam for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Shopee",
      type: "E-commerce",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+5.5%",
      changeValue: 5.5,
      description: "A fast-growing e-commerce platform dominant in Southeast Asia.",
    },
    {
      rank: 4,
      name: "Lazada",
      type: "E-commerce",
      monthlyVisits: "1.2B",
      monthlyVisitsValue: 1200,
      change: "+3.0%",
      changeValue: 3.0,
      description: "A popular online shopping destination in Vietnam for various products.",
    },
    {
      rank: 5,
      name: "Tiki",
      type: "E-commerce",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A popular online shopping destination in Vietnam for various products.",
    },
    {
      rank: 6,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "-1.2%",
      changeValue: -1.2,
      description: "A major social networking platform widely used across Vietnam for community and news.",
    },
    {
      rank: 7,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "680M",
      monthlyVisitsValue: 680,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Vietnamese students, researchers, and readers.",
    },
    {
      rank: 8,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A fast-growing visual social platform popular among Vietnamese youth for reels and stories.",
    },
    {
      rank: 9,
      name: "TikTok",
      type: "Social Network",
      monthlyVisits: "550M",
      monthlyVisitsValue: 550,
      change: "+8.5%",
      changeValue: 8.5,
      description: "A fast-growing short-video platform dominating Vietnamese youth attention.",
    },
    {
      rank: 10,
      name: "Zalo",
      type: "Messaging",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+2.0%",
      changeValue: 2.0,
      description: "A messaging platform whose web client is used in Vietnam.",
    },
    {
      rank: 11,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A premium streaming service investing in Vietnamese original content.",
    },
    {
      rank: 12,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+2.8%",
      changeValue: 2.8,
      description: "The professional networking hub for Vietnamese job seekers, recruiters, and B2B content.",
    },
    {
      rank: 13,
      name: "VNExpress",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 14,
      name: "Tuoi Tre",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 15,
      name: "Thanh Nien",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 16,
      name: "Dan Tri",
      type: "News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 17,
      name: "VnMedia",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 18,
      name: "Bao Moi",
      type: "News",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 19,
      name: "24H",
      type: "News",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 20,
      name: "Kenh14",
      type: "Entertainment",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.5%",
      changeValue: 0.5,
      description: "An entertainment platform popular in Vietnam.",
    },
    {
      rank: 21,
      name: "Zing News",
      type: "News",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 22,
      name: "VTC News",
      type: "News",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 23,
      name: "Vietnamnet",
      type: "News",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 24,
      name: "Nguoi Lao Dong",
      type: "News",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 25,
      name: "Bao Dat Viet",
      type: "News",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 26,
      name: "Lao Dong",
      type: "News",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 27,
      name: "Cong An Nhan Dan",
      type: "News",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 28,
      name: "Quan Doi Nhan Dan",
      type: "News",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Vietnamese and international headlines.",
    },
    {
      rank: 29,
      name: "Bongda24h",
      type: "Sports",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A sports media site covering Vietnamese and international sports.",
    },
    {
      rank: 30,
      name: "Xoilac",
      type: "Sports",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A sports media site covering Vietnamese and international sports.",
    },
    {
      rank: 31,
      name: "Vebo",
      type: "Sports",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A sports media site covering Vietnamese and international sports.",
    },
    {
      rank: 32,
      name: "TrueSport",
      type: "Sports",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A sports media site covering Vietnamese and international sports.",
    },
    {
      rank: 33,
      name: "Tructiepbongda",
      type: "Sports",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A sports media site covering Vietnamese and international sports.",
    },
    {
      rank: 34,
      name: "Sctv",
      type: "Media",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Vietnam.",
    },
    {
      rank: 35,
      name: "VTV",
      type: "Media",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Vietnam.",
    },
    {
      rank: 36,
      name: "HTV",
      type: "Media",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A media company's digital platform in Vietnam.",
    },
    {
      rank: 37,
      name: "VTC",
      type: "Media",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Vietnam.",
    },
    {
      rank: 38,
      name: "VOV",
      type: "Media",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A media company's digital platform in Vietnam.",
    },
    {
      rank: 39,
      name: "Bao Dien Tu Chinh Phu",
      type: "Government",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+0.3%",
      changeValue: 0.3,
      description: "An official government service portal in Vietnam.",
    },
    {
      rank: 40,
      name: "Tong Cuc Thong Ke",
      type: "Government",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.2%",
      changeValue: 0.2,
      description: "An official government service portal in Vietnam.",
    },
    {
      rank: 41,
      name: "Vietcombank",
      type: "Banking",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 42,
      name: "BIDV",
      type: "Banking",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 43,
      name: "Vietinbank",
      type: "Banking",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 44,
      name: "Techcombank",
      type: "Banking",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 45,
      name: "MB Bank",
      type: "Banking",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+0.7%",
      changeValue: 0.7,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 46,
      name: "VPBank",
      type: "Banking",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 47,
      name: "ACB",
      type: "Banking",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Vietnam.",
    },
    {
      rank: 48,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A global accommodation booking platform widely used by Vietnamese travelers.",
    },
    {
      rank: 49,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "1.5M",
      monthlyVisitsValue: 1.5,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 50,
      name: "Agoda",
      type: "Travel",
      monthlyVisits: "1M",
      monthlyVisitsValue: 1,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Vietnamese travelers.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Vietnam IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Vietnam.",
    "E-commerce is led by Shopee, Lazada, Tiki, reflecting Vietnamese shopping habits.",
    "TikTok shows the fastest growth at +8.5% month-over-month.",
    "News and media sites maintain strong daily traffic from Vietnamese readers.",
    "Government and banking portals see steady usage across Vietnam.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Vietnam", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Vietnam in 2026?",
      answer: "In 2026, the most visited websites in Vietnam are led by Google, YouTube, Shopee, followed by Shopee and local platforms like Lazada, Tiki, Zalo. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Vietnam have in 2026?",
      answer: "Vietnam has over 80 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Vietnam?",
      answer: "Shopee is the most visited e-commerce site in Vietnam, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Vietnam?",
      answer: "Google is among the most visited websites in Vietnam. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Vietnam?",
      answer: "The top local websites in Vietnam include Lazada, Tiki, Zalo, which compete alongside global platforms for Vietnamese users' attention.",
    },
    {
      question: "How is the traffic data for Vietnam websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Vietnam IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
