import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-netherlands";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Netherlands [2026]",
  description: "Discover the 50 most visited websites in Netherlands in 2026, ranked by estimated monthly visits. See how Google, YouTube, Bol.com and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Netherlands [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Netherlands in 2026, ranked by estimated monthly visits. See how Google, YouTube, Bol.com and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Netherlands [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Netherlands in 2026, ranked by estimated monthly visits. See how Google, YouTube, Bol.com and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Netherlands",
  year: "2026",
  introduction: "Netherlands has over 17 million internet users, and its web traffic in 2026 reflects global platforms alongside local retail and media leaders. This ranking lists the 50 most visited websites in Netherlands for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "2.2B",
      monthlyVisitsValue: 2200,
      change: "+1.2%",
      changeValue: 1.2,
      description: "The leading search engine in Netherlands, handling the vast majority of Dutch web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+2.5%",
      changeValue: 2.5,
      description: "The dominant video platform in Netherlands for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Bol.com",
      type: "E-commerce",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+2.8%",
      changeValue: 2.8,
      description: "A popular online shopping destination in Netherlands for various products.",
    },
    {
      rank: 4,
      name: "Marktplaats",
      type: "Classifieds",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A classifieds platform for buying and selling in Netherlands.",
    },
    {
      rank: 5,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "680M",
      monthlyVisitsValue: 680,
      change: "-1.5%",
      changeValue: -1.5,
      description: "A major social networking platform widely used across Netherlands for community and news.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "620M",
      monthlyVisitsValue: 620,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Dutch students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "550M",
      monthlyVisitsValue: 550,
      change: "+3.8%",
      changeValue: 3.8,
      description: "A fast-growing visual social platform popular among Dutch youth for reels and stories.",
    },
    {
      rank: 8,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "-1.8%",
      changeValue: -1.8,
      description: "The real-time public conversation platform widely used for news in Netherlands.",
    },
    {
      rank: 9,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+2.2%",
      changeValue: 2.2,
      description: "A premium streaming service investing in Dutch original content.",
    },
    {
      rank: 10,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+2.5%",
      changeValue: 2.5,
      description: "The professional networking hub for Dutch job seekers, recruiters, and B2B content.",
    },
    {
      rank: 11,
      name: "NU.nl",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 12,
      name: "NOS",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 13,
      name: "Telegraaf",
      type: "News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 14,
      name: "AD",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 15,
      name: "Volkskrant",
      type: "News",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 16,
      name: "NRC",
      type: "News",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 17,
      name: "Parool",
      type: "News",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 18,
      name: "Trouw",
      type: "News",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 19,
      name: "RTL Nieuws",
      type: "News",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 20,
      name: "BNR",
      type: "Business News",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A business news publication in Netherlands.",
    },
    {
      rank: 21,
      name: "AT5",
      type: "News",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Dutch and international headlines.",
    },
    {
      rank: 22,
      name: "VodafoneZiggo",
      type: "Telecom",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A telecommunications provider's official site in Netherlands.",
    },
    {
      rank: 23,
      name: "KPN",
      type: "Telecom",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A telecommunications provider's official site in Netherlands.",
    },
    {
      rank: 24,
      name: "T-Mobile",
      type: "Telecom",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A telecommunications provider's official site in Netherlands.",
    },
    {
      rank: 25,
      name: "Odido",
      type: "Telecom",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A telecommunications provider's official site in Netherlands.",
    },
    {
      rank: 26,
      name: "Caiway",
      type: "Telecom",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A telecommunications provider's official site in Netherlands.",
    },
    {
      rank: 27,
      name: "Delta",
      type: "Telecom",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A telecommunications provider's official site in Netherlands.",
    },
    {
      rank: 28,
      name: "Rabobank",
      type: "Banking",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 29,
      name: "ING",
      type: "Banking",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 30,
      name: "ABN AMRO",
      type: "Banking",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 31,
      name: "SNS Bank",
      type: "Banking",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 32,
      name: "ASN Bank",
      type: "Banking",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 33,
      name: "Triodos",
      type: "Banking",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 34,
      name: "Knab",
      type: "Banking",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 35,
      name: "Bunq",
      type: "Banking",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A leading bank's online banking portal in Netherlands.",
    },
    {
      rank: 36,
      name: "Funda",
      type: "Real Estate",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+1.2%",
      changeValue: 1.2,
      description: "A property listing portal popular in Netherlands.",
    },
    {
      rank: 37,
      name: "Jaap.nl",
      type: "Real Estate",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A property listing portal popular in Netherlands.",
    },
    {
      rank: 38,
      name: "Pararius",
      type: "Real Estate",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A property listing portal popular in Netherlands.",
    },
    {
      rank: 39,
      name: "Kamernet",
      type: "Real Estate",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A property listing portal popular in Netherlands.",
    },
    {
      rank: 40,
      name: "ANWB",
      type: "Travel",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A travel booking platform widely used by Dutch travelers.",
    },
    {
      rank: 41,
      name: "NS",
      type: "Travel",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A travel booking platform widely used by Dutch travelers.",
    },
    {
      rank: 42,
      name: "KLM",
      type: "Travel",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A travel booking platform widely used by Dutch travelers.",
    },
    {
      rank: 43,
      name: "Transavia",
      type: "Travel",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A travel booking platform widely used by Dutch travelers.",
    },
    {
      rank: 44,
      name: "Corendon",
      type: "Travel",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A travel booking platform widely used by Dutch travelers.",
    },
    {
      rank: 45,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A global accommodation booking platform widely used by Dutch travelers.",
    },
    {
      rank: 46,
      name: "Tripadvisor",
      type: "Travel",
      monthlyVisits: "1.5M",
      monthlyVisitsValue: 1.5,
      change: "-0.2%",
      changeValue: -0.2,
      description: "A travel review and booking site for hotels, restaurants, and attractions.",
    },
    {
      rank: 47,
      name: "Weeronline",
      type: "Weather",
      monthlyVisits: "1.2M",
      monthlyVisitsValue: 1.2,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A weather forecast site widely used in Netherlands.",
    },
    {
      rank: 48,
      name: "Buienradar",
      type: "Weather",
      monthlyVisits: "1M",
      monthlyVisitsValue: 1,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A weather forecast site widely used in Netherlands.",
    },
    {
      rank: 49,
      name: "Pathe",
      type: "Entertainment",
      monthlyVisits: "0.8M",
      monthlyVisitsValue: 0.8,
      change: "+0.5%",
      changeValue: 0.5,
      description: "An entertainment platform popular in Netherlands.",
    },
    {
      rank: 50,
      name: "Albert Heijn",
      type: "Retail",
      monthlyVisits: "0.5M",
      monthlyVisitsValue: 0.5,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Netherlands.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Netherlands IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Netherlands.",
    "E-commerce is led by Bol.com, reflecting Dutch shopping habits.",
    "Instagram shows the fastest growth at +3.8% month-over-month.",
    "News and media sites maintain strong daily traffic from Dutch readers.",
    "Government and banking portals see steady usage across Netherlands.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Netherlands", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Netherlands in 2026?",
      answer: "In 2026, the most visited websites in Netherlands are led by Google, YouTube, Bol.com, followed by Bol.com and local platforms like Bol.com, Marktplaats, NU.nl. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Netherlands have in 2026?",
      answer: "Netherlands has over 17 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Netherlands?",
      answer: "Bol.com is the most visited e-commerce site in Netherlands, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Netherlands?",
      answer: "Google is among the most visited websites in Netherlands. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Netherlands?",
      answer: "The top local websites in Netherlands include Bol.com, Marktplaats, NU.nl, which compete alongside global platforms for Dutch users' attention.",
    },
    {
      question: "How is the traffic data for Netherlands websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Netherlands IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
