import type { Metadata } from "next";
import { WebsiteListTemplate } from "@/components/listing/templates/WebsiteListTemplate";
import type { WebsiteListData } from "@/lib/listing/types";

const SLUG = "most-visited-websites-in-saudi-arabia";
const PAGE_URL = `https://www.trending-hot.com/${SLUG}`;

export const metadata: Metadata = {
  title: "Most Visited Websites in Saudi Arabia [2026]",
  description: "Discover the 50 most visited websites in Saudi Arabia in 2026, ranked by estimated monthly visits. See how Google, YouTube, Aramco and more compare.",
  metadataBase: new URL("https://www.trending-hot.com"),
  alternates: {
    canonical: `/${SLUG}`,
  },
  openGraph: {
    title: "Most Visited Websites in Saudi Arabia [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Saudi Arabia in 2026, ranked by estimated monthly visits. See how Google, YouTube, Aramco and more compare.",
    url: PAGE_URL,
    siteName: "Trending Hot",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Most Visited Websites in Saudi Arabia [2026] | Trending Hot",
    description: "Discover the 50 most visited websites in Saudi Arabia in 2026, ranked by estimated monthly visits. See how Google, YouTube, Aramco and more compare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const data: WebsiteListData = {
  type: "D",
  country: "Saudi Arabia",
  year: "2026",
  introduction: "Saudi Arabia has over 35 million internet users, and its web traffic in 2026 reflects global platforms alongside local media and government services. This ranking lists the 50 most visited websites in Saudi Arabia for 2026, ordered by estimated monthly visits. Alongside international heavyweights, you will find domestic leaders that dominate their categories locally. Each entry includes the site category, monthly visit estimate, and month-over-month change so you can spot which platforms are climbing and which are cooling off.",
  websites: [
    {
      rank: 1,
      name: "Google",
      type: "Search Engine",
      monthlyVisits: "1.8B",
      monthlyVisitsValue: 1800,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The leading search engine in Saudi Arabia, handling the vast majority of Saudi web queries.",
    },
    {
      rank: 2,
      name: "YouTube",
      type: "Video Platform",
      monthlyVisits: "1.5B",
      monthlyVisitsValue: 1500,
      change: "+3.2%",
      changeValue: 3.2,
      description: "The dominant video platform in Saudi Arabia for entertainment, music, and education.",
    },
    {
      rank: 3,
      name: "Aramco",
      type: "Business News",
      monthlyVisits: "980M",
      monthlyVisitsValue: 980,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A business news publication in Saudi Arabia.",
    },
    {
      rank: 4,
      name: "Sabic",
      type: "Business News",
      monthlyVisits: "850M",
      monthlyVisitsValue: 850,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A business news publication in Saudi Arabia.",
    },
    {
      rank: 5,
      name: "Facebook",
      type: "Social Network",
      monthlyVisits: "780M",
      monthlyVisitsValue: 780,
      change: "-1.2%",
      changeValue: -1.2,
      description: "A major social networking platform widely used across Saudi Arabia for community and news.",
    },
    {
      rank: 6,
      name: "Wikipedia",
      type: "Reference",
      monthlyVisits: "720M",
      monthlyVisitsValue: 720,
      change: "+0.5%",
      changeValue: 0.5,
      description: "The free encyclopedia accessed heavily by Saudi students, researchers, and readers.",
    },
    {
      rank: 7,
      name: "Instagram",
      type: "Social Network",
      monthlyVisits: "650M",
      monthlyVisitsValue: 650,
      change: "+4.0%",
      changeValue: 4.0,
      description: "A fast-growing visual social platform popular among Saudi youth for reels and stories.",
    },
    {
      rank: 8,
      name: "Twitter / X",
      type: "Social Network",
      monthlyVisits: "580M",
      monthlyVisitsValue: 580,
      change: "+1.5%",
      changeValue: 1.5,
      description: "The real-time public conversation platform widely used for news in Saudi Arabia.",
    },
    {
      rank: 9,
      name: "Netflix",
      type: "Streaming",
      monthlyVisits: "520M",
      monthlyVisitsValue: 520,
      change: "+2.8%",
      changeValue: 2.8,
      description: "A premium streaming service investing in Saudi original content.",
    },
    {
      rank: 10,
      name: "LinkedIn",
      type: "Professional Network",
      monthlyVisits: "480M",
      monthlyVisitsValue: 480,
      change: "+2.5%",
      changeValue: 2.5,
      description: "The professional networking hub for Saudi job seekers, recruiters, and B2B content.",
    },
    {
      rank: 11,
      name: "Al Arabiya",
      type: "News",
      monthlyVisits: "420M",
      monthlyVisitsValue: 420,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 12,
      name: "Al Ekhbariya",
      type: "News",
      monthlyVisits: "380M",
      monthlyVisitsValue: 380,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 13,
      name: "Okaz",
      type: "News",
      monthlyVisits: "350M",
      monthlyVisitsValue: 350,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 14,
      name: "Asharq Al-Awsat",
      type: "News",
      monthlyVisits: "320M",
      monthlyVisitsValue: 320,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 15,
      name: "Al Riyadh",
      type: "News",
      monthlyVisits: "280M",
      monthlyVisitsValue: 280,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 16,
      name: "Al Jazirah",
      type: "News",
      monthlyVisits: "250M",
      monthlyVisitsValue: 250,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 17,
      name: "Al Watan",
      type: "News",
      monthlyVisits: "220M",
      monthlyVisitsValue: 220,
      change: "-0.1%",
      changeValue: -0.1,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 18,
      name: "Al Madina",
      type: "News",
      monthlyVisits: "200M",
      monthlyVisitsValue: 200,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 19,
      name: "Al Youm",
      type: "News",
      monthlyVisits: "180M",
      monthlyVisitsValue: 180,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 20,
      name: "Al Bilad",
      type: "News",
      monthlyVisits: "160M",
      monthlyVisitsValue: 160,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A major news website covering Saudi and international headlines.",
    },
    {
      rank: 21,
      name: "MBC",
      type: "Media",
      monthlyVisits: "140M",
      monthlyVisitsValue: 140,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A media company's digital platform in Saudi Arabia.",
    },
    {
      rank: 22,
      name: "SBC",
      type: "Media",
      monthlyVisits: "120M",
      monthlyVisitsValue: 120,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A media company's digital platform in Saudi Arabia.",
    },
    {
      rank: 23,
      name: "Rotana",
      type: "Media",
      monthlyVisits: "105M",
      monthlyVisitsValue: 105,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A media company's digital platform in Saudi Arabia.",
    },
    {
      rank: 24,
      name: "Shahid",
      type: "Streaming",
      monthlyVisits: "95M",
      monthlyVisitsValue: 95,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A streaming service popular among Saudi viewers.",
    },
    {
      rank: 25,
      name: "Netflix MENA",
      type: "Streaming",
      monthlyVisits: "85M",
      monthlyVisitsValue: 85,
      change: "+1.8%",
      changeValue: 1.8,
      description: "A streaming service popular among Saudi viewers.",
    },
    {
      rank: 26,
      name: "StarzPlay Arabia",
      type: "Streaming",
      monthlyVisits: "78M",
      monthlyVisitsValue: 78,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A streaming service popular among Saudi viewers.",
    },
    {
      rank: 27,
      name: "Jawwy",
      type: "Telecom",
      monthlyVisits: "72M",
      monthlyVisitsValue: 72,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A telecommunications provider's official site in Saudi Arabia.",
    },
    {
      rank: 28,
      name: "stc",
      type: "Telecom",
      monthlyVisits: "65M",
      monthlyVisitsValue: 65,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A telecommunications provider's official site in Saudi Arabia.",
    },
    {
      rank: 29,
      name: "Mobily",
      type: "Telecom",
      monthlyVisits: "58M",
      monthlyVisitsValue: 58,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A telecommunications provider's official site in Saudi Arabia.",
    },
    {
      rank: 30,
      name: "Zain",
      type: "Telecom",
      monthlyVisits: "52M",
      monthlyVisitsValue: 52,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A telecommunications provider's official site in Saudi Arabia.",
    },
    {
      rank: 31,
      name: "Al Rajhi Bank",
      type: "Banking",
      monthlyVisits: "48M",
      monthlyVisitsValue: 48,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 32,
      name: "SAB",
      type: "Banking",
      monthlyVisits: "42M",
      monthlyVisitsValue: 42,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 33,
      name: "NCB",
      type: "Banking",
      monthlyVisits: "38M",
      monthlyVisitsValue: 38,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 34,
      name: "Alinma",
      type: "Banking",
      monthlyVisits: "32M",
      monthlyVisitsValue: 32,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 35,
      name: "Bank Aljazira",
      type: "Banking",
      monthlyVisits: "28M",
      monthlyVisitsValue: 28,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 36,
      name: "Riyad Bank",
      type: "Banking",
      monthlyVisits: "25M",
      monthlyVisitsValue: 25,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 37,
      name: "SNB",
      type: "Banking",
      monthlyVisits: "22M",
      monthlyVisitsValue: 22,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 38,
      name: "ANB",
      type: "Banking",
      monthlyVisits: "18M",
      monthlyVisitsValue: 18,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 39,
      name: "SABB",
      type: "Banking",
      monthlyVisits: "15M",
      monthlyVisitsValue: 15,
      change: "+0.1%",
      changeValue: 0.1,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 40,
      name: "Bank Albilad",
      type: "Banking",
      monthlyVisits: "12M",
      monthlyVisitsValue: 12,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A leading bank's online banking portal in Saudi Arabia.",
    },
    {
      rank: 41,
      name: "Amazon Saudi Arabia",
      type: "E-commerce",
      monthlyVisits: "10M",
      monthlyVisitsValue: 10,
      change: "+3.5%",
      changeValue: 3.5,
      description: "Amazon's Saudi storefront, a growing e-commerce presence.",
    },
    {
      rank: 42,
      name: "Noon",
      type: "E-commerce",
      monthlyVisits: "8M",
      monthlyVisitsValue: 8,
      change: "+2.5%",
      changeValue: 2.5,
      description: "A popular online shopping destination in Saudi Arabia for various products.",
    },
    {
      rank: 43,
      name: "Jarir",
      type: "Retail",
      monthlyVisits: "6M",
      monthlyVisitsValue: 6,
      change: "+0.8%",
      changeValue: 0.8,
      description: "A retail brand's online store in Saudi Arabia.",
    },
    {
      rank: 44,
      name: "Extra",
      type: "Retail",
      monthlyVisits: "5M",
      monthlyVisitsValue: 5,
      change: "+0.5%",
      changeValue: 0.5,
      description: "A retail brand's online store in Saudi Arabia.",
    },
    {
      rank: 45,
      name: "Lulu Hypermarket",
      type: "Retail",
      monthlyVisits: "4M",
      monthlyVisitsValue: 4,
      change: "+0.6%",
      changeValue: 0.6,
      description: "A retail brand's online store in Saudi Arabia.",
    },
    {
      rank: 46,
      name: "Panda",
      type: "Retail",
      monthlyVisits: "3M",
      monthlyVisitsValue: 3,
      change: "+0.4%",
      changeValue: 0.4,
      description: "A retail brand's online store in Saudi Arabia.",
    },
    {
      rank: 47,
      name: "Othaim",
      type: "Retail",
      monthlyVisits: "2.5M",
      monthlyVisitsValue: 2.5,
      change: "+0.3%",
      changeValue: 0.3,
      description: "A retail brand's online store in Saudi Arabia.",
    },
    {
      rank: 48,
      name: "Danube",
      type: "Retail",
      monthlyVisits: "2M",
      monthlyVisitsValue: 2,
      change: "+0.2%",
      changeValue: 0.2,
      description: "A retail brand's online store in Saudi Arabia.",
    },
    {
      rank: 49,
      name: "Booking.com",
      type: "Travel",
      monthlyVisits: "1.5M",
      monthlyVisitsValue: 1.5,
      change: "+1.0%",
      changeValue: 1.0,
      description: "A global accommodation booking platform widely used by Saudi travelers.",
    },
    {
      rank: 50,
      name: "Careem",
      type: "Services",
      monthlyVisits: "1M",
      monthlyVisitsValue: 1,
      change: "+1.5%",
      changeValue: 1.5,
      description: "A services platform widely used in Saudi Arabia.",
    },
  ],
  methodology: "This ranking was compiled in July 2026 by the Trending Hot editorial team using a combination of third-party traffic-estimation tools (similar to Similarweb and Semrush), publicly reported audience figures, and internal modeling. Monthly visit estimates reflect domain-level visits from Saudi Arabia IP addresses for the trailing 30-day window, including subdomains where applicable. Change values represent month-over-month movement in estimated visits. Figures are modeled approximations rather than exact analytics and are intended to indicate relative scale and momentum; actual visit counts held by the publishers may differ. Sites serving primarily app-based traffic (such as messaging and payments) show lower web visits than their true usage. The list is updated periodically as new data becomes available.",
  tldr: [
    "Google tops the list as the most visited website in Saudi Arabia.",
    "E-commerce is led by Amazon Saudi Arabia, Noon, reflecting Saudi shopping habits.",
    "Instagram shows the fastest growth at +4.0% month-over-month.",
    "News and media sites maintain strong daily traffic from Saudi readers.",
    "Government and banking portals see steady usage across Saudi Arabia.",
  ],
  toc: [
    { id: "introduction", title: "Introduction", level: 1 },
    { id: "ranking", title: "Top 50 Most Visited Websites in Saudi Arabia", level: 1 },
    { id: "methodology", title: "Methodology", level: 1 },
    { id: "faq", title: "FAQ", level: 1 },
    { id: "related", title: "Related Rankings", level: 1 },
  ],
  faqs: [
    {
      question: "What are the most visited websites in Saudi Arabia in 2026?",
      answer: "In 2026, the most visited websites in Saudi Arabia are led by Google, YouTube, Aramco, followed by Amazon Saudi Arabia and local platforms like Aramco, Sabic, Al Arabiya. The full top 50 is ranked above by estimated monthly visits.",
    },
    {
      question: "How many internet users does Saudi Arabia have in 2026?",
      answer: "Saudi Arabia has over 35 million internet users in 2026, making it a significant online population. This drives enormous traffic to both domestic and international platforms.",
    },
    {
      question: "Which website is the most popular for online shopping in Saudi Arabia?",
      answer: "Amazon Saudi Arabia is the most visited e-commerce site in Saudi Arabia, with billions of monthly visits. Local alternatives also hold significant market share depending on the category.",
    },
    {
      question: "Is Google the most visited website in Saudi Arabia?",
      answer: "Google is among the most visited websites in Saudi Arabia. Whether it ranks first depends on the presence of dominant local portals like search engines or web portals.",
    },
    {
      question: "What are the top local websites in Saudi Arabia?",
      answer: "The top local websites in Saudi Arabia include Aramco, Sabic, Al Arabiya, which compete alongside global platforms for Saudi users' attention.",
    },
    {
      question: "How is the traffic data for Saudi Arabia websites collected?",
      answer: "Our estimates combine third-party traffic-estimation services, public audience disclosures, and internal modeling of Saudi Arabia IP-based domain visits. These are approximations showing relative scale and momentum.",
    },
  ],
  related: [
    {
      title: "Most Visited Websites in Japan",
      href: "/most-visited-websites-in-japan",
      description: "The 50 most visited websites in Japan, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in India",
      href: "/most-visited-websites-in-india",
      description: "The 50 most visited websites in India, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United States",
      href: "/most-visited-websites-in-united-states",
      description: "The 50 most visited websites in United States, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in United Kingdom",
      href: "/most-visited-websites-in-united-kingdom",
      description: "The 50 most visited websites in United Kingdom, ranked by estimated monthly visits.",
    },
    {
      title: "Most Visited Websites in Germany",
      href: "/most-visited-websites-in-germany",
      description: "The 50 most visited websites in Germany, ranked by estimated monthly visits.",
    },
  ],
  author: {
    name: "Trending Hot Team",
    role: "Editorial Team",
    date: "2026-08-01",
    readTime: "8 min read",
  },
};

export default function Page() {
  return <WebsiteListTemplate data={data} />;
}
